// TARGET X v6 — Resumo Executivo de Gestão • segunda-feira às 10:00
(function(){
  if(window.__txAlertsV60)return;window.__txAlertsV60=true;
  const ACK='tx_alert_ack_v60';let alerts=[];
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const num=v=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(v)||0));const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(v)||0);const pct=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'0%';
  const css=document.createElement('style');css.textContent=`#alertTab{position:relative}.txAlertCount{display:inline-grid;place-items:center;min-width:18px;height:18px;padding:0 5px;margin-left:5px;border-radius:999px;background:#ff697d;color:#fff;font-size:9px;font-weight:1000}.txExec{display:grid;grid-template-columns:1.1fr .9fr;gap:10px}.txExecBox{border:1px solid var(--line);border-radius:16px;padding:13px;background:#07120d}.txExecBox h3{margin:0 0 8px;font-size:12px;text-transform:uppercase}.txAlertGrid{display:grid;gap:8px}.txAlertCard{border:1px solid var(--line);border-radius:13px;padding:11px;background:#07120d}.txAlertCard.critical{border-color:#7f2634;background:#18090d}.txAlertCard.warning{border-color:#6d5d22;background:#151308}.txAlertCard.positive{border-color:#315c47;background:#07150d}.txAlertTop{display:flex;justify-content:space-between;gap:10px}.txAlertTitle{font-weight:1000;margin:3px 0}.txAlertText{font-size:11px;line-height:1.45;color:#d4e6dc}.txAlertActions{display:flex;gap:7px;margin-top:9px;flex-wrap:wrap}.txSchedule{border:1px solid #315c47;border-radius:16px;padding:16px;background:#07150d}.txSchedule b{display:block;font-size:20px;margin:5px 0}.txSchedule .next{color:var(--green)}#txAlertOverlay{display:none;position:fixed;inset:0;z-index:13000;background:#020604e8;backdrop-filter:blur(8px);padding:14px}#txAlertOverlay.open{display:grid;place-items:center}.txAlertPopup{width:min(560px,100%);border-radius:20px;padding:18px;background:linear-gradient(180deg,#160b0f,#07100c);border:1px solid #7f2634}.txAlertPopup.warning{border-color:#6d5d22}.txAlertPopup.positive{border-color:#315c47}@media(max-width:760px){.txExec{grid-template-columns:1fr}}`;document.head.appendChild(css);
  const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  function mondayOf(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function br(s){return String(s||'').split('-').reverse().join('/')}
  function inWindow(d=new Date()){return d.getDay()===1&&d.getHours()===10}
  function nextMonday10(d=new Date()){const x=new Date(d);x.setMinutes(0,0,0);x.setHours(10);let add=(1-x.getDay()+7)%7;if(add===0&&d.getHours()>=11)add=7;if(add===0&&d.getHours()<10)return x;if(add===0&&d.getHours()===10)return x;x.setDate(x.getDate()+add);return x}
  function key(type,person){return`${iso(mondayOf())}|${type}|${person||'GERAL'}`}
  function getAck(){try{return new Set(JSON.parse(localStorage.getItem(ACK)||'[]'))}catch{return new Set()}}function saveAck(s){localStorage.setItem(ACK,JSON.stringify([...s]))}
  function agg(rows){const a=blank();rows.forEach(r=>plus(a,r));return a}
  function byPerson(rows){const m={};rows.forEach(r=>{if(!r.person)return;m[r.person]||(m[r.person]=[]);m[r.person].push(r)});return m}
  function latest(){return window.TX?.getMeta?.().through||DATA_META.through}
  function dayDiff(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
  function compute(){
    const out=[],end=latest(),month=Number(end.slice(5,7))||9,day=Math.max(1,Number(end.slice(8,10))||1),people=allPeople().map(effectivePerson).filter(p=>p.active);
    const today=iso(new Date()),stale=dayDiff(end,today);if(stale>=3)out.push({key:key('base_stale'),level:'critical',title:'Planilha precisa ser atualizada',text:`A base oficial está em ${br(end)} (${stale} dias atrás). Atualize a planilha antes de usar as decisões da semana.`,metric:`Base ${br(end)}`});
    const monthRows=people.map(p=>({p,d:personMonth(p.name,month)})),totalCouples=monthRows.reduce((s,x)=>s+(Number(x.d.couples)||0),0),totalGift=monthRows.reduce((s,x)=>s+(Number(x.d.gift)||0),0),giftAvg=totalCouples?totalGift/totalCouples:0;
    monthRows.forEach(({p,d})=>{const c=Number(d.couples)||0,q=Number(d.q)||0,nq=Number(d.nq)||0,s=Number(d.sales)||0,nt=Number(d.notour)||0,g=Number(d.gift)||0,qual=q+nq,cvb=Math.max(0,c-nt),conv=cvb?s/cvb:0,nqr=qual?nq/qual:0,gpc=c?g/c:0,expected=22*Math.min(day,30)/30;if(day>=7&&c<expected*.6)out.push({key:key('pace',p.name),level:c<expected*.4?'critical':'warning',person:p.name,title:'Ritmo de casais abaixo do esperado',text:`${p.name} está com ${num(c)} casais. Ritmo de referência até o dia ${day}: ${expected.toFixed(1)}.`,metric:`${num(c)} casais`});if(qual>=5&&nqr>=.4)out.push({key:key('nq',p.name),level:nqr>=.55?'critical':'warning',person:p.name,title:'NQ elevado',text:`${p.name} está com ${(nqr*100).toFixed(0)}% de NQ (${num(nq)} de ${num(qual)}).`,metric:`Q ${num(q)} • NQ ${num(nq)}`});if(c>=8&&conv<.1)out.push({key:key('conv',p.name),level:'warning',person:p.name,title:'Conversão baixa',text:`${p.name} tem ${num(c)} casais e ${num(s)} venda(s). Conversão ${pct(s,cvb)}.`,metric:`${num(s)} vendas`});if(c>=5&&gpc>Math.max(250,giftAvg*1.35))out.push({key:key('gift',p.name),level:'warning',person:p.name,title:'Custo de brinde elevado',text:`${p.name} está em ${money(gpc)} por casal; referência atual ${money(giftAvg)}.`,metric:money(gpc)+'/casal'});if(c>=18&&c<22)out.push({key:key('near22',p.name),level:'positive',person:p.name,title:'Perto dos 22 casais',text:`${p.name} está com ${num(c)} casais. Faltam ${num(22-c)}.`,metric:`${num(c)}/22`})});
    try{const s=sepTotal(),proj=(Number(s.vgv)||0)/day*30;if(proj<METAS.vgv*.9)out.push({key:key('vgv'),level:'critical',title:'VGV abaixo do ritmo da meta',text:`Projeção ${money(proj)} contra meta de ${money(METAS.vgv)}.`,metric:`Atual ${money(s.vgv)}`});else if(proj<METAS.vgv)out.push({key:key('vgv'),level:'warning',title:'Atenção ao ritmo de VGV',text:`Projeção ${money(proj)} contra meta de ${money(METAS.vgv)}.`,metric:`Atual ${money(s.vgv)}`})}catch{}
    const rows=window.TX?.getRows?.()||[],mon=mondayOf(),lastStart=iso(addDays(mon,-7)),lastEnd=iso(addDays(mon,-1)),prevStart=iso(addDays(mon,-14)),prevEnd=iso(addDays(mon,-8)),last=byPerson(rows.filter(r=>r.date>=lastStart&&r.date<=lastEnd)),prev=byPerson(rows.filter(r=>r.date>=prevStart&&r.date<=prevEnd));Object.keys(last).forEach(name=>{const a=agg(last[name]),b=agg(prev[name]||[]);if(a.couples>=5&&b.couples>=3&&a.couples>=b.couples*1.3)out.push({key:key('growth',name),level:'positive',person:name,title:'Evolução semanal',text:`${name} subiu de ${num(b.couples)} para ${num(a.couples)} casais na última semana.`,metric:`+${pct(a.couples-b.couples,b.couples)}`})});
    const sev={critical:0,warning:1,positive:2};return out.sort((a,b)=>sev[a.level]-sev[b.level]||String(a.person||'').localeCompare(String(b.person||'')));
  }
  function pending(){const ack=getAck();alerts=compute();return alerts.filter(a=>!ack.has(a.key))}
  function acknowledge(a){const s=getAck();s.add(a.key);saveAck(s);const ov=$('txAlertOverlay');if(ov){ov.classList.remove('open');ov.innerHTML=''}render();setTimeout(showNext,100)}
  function openPerson(name){if(!name)return;const sel=$('profilePerson');if(sel&&[...sel.options].some(o=>o.value===name)){sel.value=name;show('profile')}}
  function card(a){const icon=a.level==='critical'?'🔴':a.level==='warning'?'🟡':'🟢';return`<div class="txAlertCard ${a.level}"><div class="txAlertTop"><div><div class="label">${icon} ${a.level==='critical'?'CRÍTICO':a.level==='warning'?'ATENÇÃO':'OPORTUNIDADE'}</div><div class="txAlertTitle">${esc(a.title)}</div></div><b>${esc(a.metric||'')}</b></div><div class="txAlertText">${esc(a.text)}</div><div class="txAlertActions">${a.person?`<button data-alert-person="${encodeURIComponent(a.person)}">Abrir profissional</button>`:''}<button class="primary" data-alert-ack="${encodeURIComponent(a.key)}">Entendido</button></div></div>`}
  function bind(){document.querySelectorAll('[data-alert-ack]').forEach(b=>b.onclick=()=>{const a=alerts.find(x=>x.key===decodeURIComponent(b.dataset.alertAck));if(a)acknowledge(a)});document.querySelectorAll('[data-alert-person]').forEach(b=>b.onclick=()=>openPerson(decodeURIComponent(b.dataset.alertPerson)))}
  function schedule(){const c=$('txAlertCount');if(c)c.remove();$('txAlertSummary').innerHTML='';$('txAlertPeriod').textContent='Rotina semanal';$('txAlertList').innerHTML=`<div class="txSchedule"><span class="label">PRÓXIMA ANÁLISE</span><b>Alertas somente segunda-feira às 10:00</b><div>Próxima abertura: <span class="next">${nextMonday10().toLocaleString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</span></div><div class="tiny" style="margin-top:8px">Atualize a planilha oficial antes do horário. A janela automática é de 10:00 até 10:59.</div></div>`}
  function render(){if(!inWindow()){schedule();return[]}const p=pending(),crit=p.filter(x=>x.level==='critical'),warn=p.filter(x=>x.level==='warning'),pos=p.filter(x=>x.level==='positive');$('txAlertSummary').innerHTML=`<div class="stats">${stat('Críticos',num(crit.length))}${stat('Atenção',num(warn.length))}${stat('Oportunidades',num(pos.length))}${stat('Base até',br(latest()))}</div><div class="txExec" style="margin-top:10px"><div class="txExecBox"><h3>3 prioridades da gestão</h3><div class="txAlertGrid">${[...crit,...warn].slice(0,3).map(card).join('')||'<div class="empty">Sem prioridade crítica.</div>'}</div></div><div class="txExecBox"><h3>Oportunidades</h3><div class="txAlertGrid">${pos.slice(0,3).map(card).join('')||'<div class="empty">Sem oportunidade destacada.</div>'}</div></div></div>`;$('txAlertPeriod').textContent=`Segunda 10:00 • base ${br(latest())}`;$('txAlertList').innerHTML=`<div class="txAlertGrid">${p.map(card).join('')||'<div class="empty">Nenhum alerta pendente.</div>'}</div>`;bind();return p}
  function showNext(){if(!inWindow())return;const p=render(),ov=$('txAlertOverlay');if(!ov||ov.classList.contains('open'))return;const a=p.find(x=>x.level!=='positive')||p[0];if(!a)return;ov.innerHTML=`<div class="txAlertPopup ${a.level}"><div class="label">RESUMO DE GESTÃO • SEGUNDA 10:00</div><h2>${esc(a.title)}</h2><div class="txAlertText">${esc(a.text)}</div><div class="card" style="margin-top:12px"><b>${esc(a.metric||'')}</b></div><div class="txAlertActions">${a.person?'<button id="txPopPerson">Abrir profissional</button>':''}<button class="primary" id="txPopOk">✓ Entendido</button></div></div>`;ov.classList.add('open');$('txPopOk').onclick=()=>acknowledge(a);if($('txPopPerson'))$('txPopPerson').onclick=()=>openPerson(a.person)}
  function mount(){if(!$('txAlertOverlay')){const o=document.createElement('div');o.id='txAlertOverlay';document.body.appendChild(o)}render();if(inWindow())setTimeout(showNext,900)}
  window.TXAlerts={render,compute,showNext};window.addEventListener('targetx:data-updated',render);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();