const $=id=>document.getElementById(id);
const money=(v,d=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:d}).format(Number(v)||0);
const num=v=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(v)||0));
const pct=(a,b)=>b?((Number(a)||0)/(Number(b)||1)*100).toFixed(1)+'%':'0%';
const METAS={couples:370,sales:101,vgv:8500000};
const MONTH_NAMES=['','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const OFFICIAL_STORE='tx_official_daily_v60',OFFICIAL_META='tx_official_meta_v60';

// Limpeza definitiva de fluxos antigos que não existem mais na v6.
['tx_launches_v40','tx_notes_v40','tx_alert_ack_v45'].forEach(k=>localStorage.removeItem(k));

let OFFICIAL_ROWS=readJSON(OFFICIAL_STORE,[]),OFFICIAL_INFO=readJSON(OFFICIAL_META,null);
function readJSON(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}}
function blank(){return{couples:0,q:0,nq:0,sales:0,cancelled:0,vgv:0,vgv_general:0,gift:0,notour:0,attendances:0}}
function clone(o){return JSON.parse(JSON.stringify(o))}
function plus(a,b){Object.keys(blank()).forEach(k=>a[k]=(Number(a[k])||0)+(Number(b?.[k])||0));return a}
function aggregateRows(rows){return rows.reduce((a,r)=>plus(a,r),blank())}
function hasOfficialRows(){return Array.isArray(OFFICIAL_ROWS)&&OFFICIAL_ROWS.length>0}
function currentMeta(){return hasOfficialRows()?{from:OFFICIAL_INFO?.from||OFFICIAL_ROWS.map(r=>r.date).sort()[0],through:OFFICIAL_INFO?.latest||OFFICIAL_ROWS.map(r=>r.date).sort().at(-1),records:Number(OFFICIAL_INFO?.rows)||aggregateRows(OFFICIAL_ROWS).couples,source:OFFICIAL_INFO?.file||'Planilha oficial importada'}:{from:DATA_META.from,through:DATA_META.through,records:DATA_META.records,source:DATA_META.source||'Base oficial consolidada'}}
function personInfo(name){let p=clone(HIST.find(x=>x.name===name)||{name,active:true,group:'A DEFINIR',role:'CAPTADOR'});if(name==='RENAN MARCONDES JOHAS'){p.active=true;p.group='FELIPE'}return p}
function baseTotal(){return hasOfficialRows()?aggregateRows(OFFICIAL_ROWS):HIST.reduce((a,x)=>plus(a,x),blank())}
function annualTotal(){return baseTotal()}
function monthTotal(m){if(hasOfficialRows())return aggregateRows(OFFICIAL_ROWS.filter(r=>Number(String(r.date||'').slice(5,7))===Number(m)));return clone(MONTHS.find(x=>Number(x.month)===Number(m))||blank())}
function baseSep(){return monthTotal(9)}
function sepTotal(){return monthTotal(9)}
function effectivePerson(name){const p=personInfo(name);const m=hasOfficialRows()?aggregateRows(OFFICIAL_ROWS.filter(r=>r.person===name)):clone(HIST.find(x=>x.name===name)||blank());return {...p,...m,name:p.name||name,active:p.active!==false,group:p.group||'A DEFINIR',role:p.role||'CAPTADOR'}}
function personMonth(name,m){if(hasOfficialRows())return aggregateRows(OFFICIAL_ROWS.filter(r=>r.person===name&&Number(String(r.date||'').slice(5,7))===Number(m)));return clone((PERSON_MONTHS[name]&&PERSON_MONTHS[name][String(m)])||blank())}
function allPeople(){const s=new Set(HIST.map(x=>x.name));if(hasOfficialRows())OFFICIAL_ROWS.forEach(r=>r.person&&s.add(r.person));return [...s].sort()}
function convBase(x){return Math.max(0,(Number(x.couples)||0)-(Number(x.notour)||0))}
function conv(x){return pct(x.sales,convBase(x))}
function stat(label,value,small=''){return `<div class="card stat"><span class="label">${label}</span><b>${value}</b>${small?`<small>${small}</small>`:''}</div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

function show(p){
  document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));
  document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===p));
  if(p==='dashboard')renderDashboard();else if(p==='rank')renderRank();else if(p==='calendar')renderCalendar();else if(p==='profile')renderProfile();else if(p==='september')renderSeptember();else if(p==='captain')window.renderCaptain?.();else if(p==='alerts')window.TXAlerts?.render?.();else if(p==='teams')renderTeams();else if(p==='inactive')renderInactive();
}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.page));

function renderHeader(){const m=currentMeta();$('headerMeta').textContent=`Base ${String(m.from).split('-').reverse().join('/')} até ${String(m.through).split('-').reverse().join('/')} • ${num(m.records)} registros`;$('heroRange').textContent=`${String(m.from).slice(5).split('-').reverse().join('/')} → ${String(m.through).slice(5).split('-').reverse().join('/')}`;$('baseSource').textContent=hasOfficialRows()?'Planilha carregada':'Base consolidada'}
function renderDashboard(){
  renderHeader();const a=annualTotal(),s=sepTotal(),m=currentMeta(),day=Math.max(1,Number(String(m.through).slice(8,10))||1),remain=Math.max(1,30-day),proj={couples:s.couples/day*30,sales:s.sales/day*30,vgv:s.vgv/day*30};
  $('annualStats').innerHTML=[stat('Casais',num(a.couples),`${num(a.q)} Q • ${num(a.nq)} NQ`),stat('Vendas ativas',num(a.sales),`Conversão ${conv(a)}`),stat('VGV Ativo',money(a.vgv),`Ticket ${money(a.sales?a.vgv/a.sales:0)}`),stat('VGV Geral',money(a.vgv_general)),stat('Cancelamentos',num(a.cancelled)),stat('NoTour',num(a.notour)),stat('Brindes',money(a.gift),`Custo/casal ${money(a.couples?a.gift/a.couples:0,2)}`)].join('');
  $('sepProgress').innerHTML=[progressStat('Casais',s.couples,METAS.couples,proj.couples),progressStat('Vendas',s.sales,METAS.sales,proj.sales),progressStat('VGV Ativo',s.vgv,METAS.vgv,proj.vgv,true),stat('Necessário/dia',money(Math.max(0,METAS.vgv-s.vgv)/remain),`${Math.max(0,(METAS.couples-s.couples)/remain).toFixed(1)} casais • ${Math.max(0,(METAS.sales-s.sales)/remain).toFixed(1)} vendas`)].join('');
  const mm=Array.from({length:9},(_,i)=>({month:i+1,...monthTotal(i+1)})),max=Math.max(1,...mm.map(x=>x.vgv));$('vgvBars').innerHTML=mm.map(x=>`<div class="barrow"><span>${MONTH_NAMES[x.month]}</span><div class="bartrack"><div class="barfill" style="width:${x.vgv/max*100}%"></div></div><b>${money(x.vgv)}</b></div>`).join('');
  const best=[...mm].sort((x,y)=>y.vgv-x.vgv)[0],leader=activeSepRanking()[0];$('insights').innerHTML=`<div class="insight"><b>Melhor mês</b>${MONTH_NAMES[best.month]} • ${money(best.vgv)} VGV ativo • ${num(best.sales)} vendas.</div><div class="insight"><b>Projeção de setembro</b>${money(proj.vgv)} • ${num(proj.sales)} vendas • ${num(proj.couples)} casais.</div><div class="insight"><b>Líder de setembro</b>${leader?esc(leader.name)+' • '+money(leader.vgv):'Sem dados'}.</div><div class="insight"><b>Ritmo da meta</b>${proj.vgv>=METAS.vgv?'<span class="green">Acima do ritmo.</span>':'<span class="amber">Abaixo do ritmo necessário.</span>'}</div>`;
}
function progressStat(label,actual,target,projection,isMoney=false){const pc=Math.min(100,target?actual/target*100:0);return `<div class="card stat"><span class="label">${label}</span><b>${isMoney?money(actual):num(actual)} <span class="tiny">/ ${isMoney?money(target):num(target)}</span></b><div class="progress ${projection>=target?'':'amber'}"><i style="width:${pc}%"></i></div><small>Projeção: ${isMoney?money(projection):num(projection)} • ${pc.toFixed(1)}%</small></div>`}

function filteredRank(){const period=$('rankPeriod')?.value||'year',q=($('rankSearch')?.value||'').trim().toUpperCase(),st=$('rankStatus')?.value||'active',k=$('rankMetric')?.value||'vgv_general';let arr=allPeople().map(n=>period==='year'?effectivePerson(n):{...effectivePerson(n),...personMonth(n,Number(period)),name:n});if(q)arr=arr.filter(x=>x.name.includes(q));if(st==='active')arr=arr.filter(x=>x.active);if(st==='inactive')arr=arr.filter(x=>!x.active);arr.sort((x,y)=>k==='conversion'?(y.sales/(convBase(y)||1))-(x.sales/(convBase(x)||1)):(Number(y[k])||0)-(Number(x[k])||0));return arr}
function renderRank(){const a=filteredRank(),tot=a.reduce((z,x)=>plus(z,x),blank()),p=$('rankPeriod')?.value||'year',title=document.querySelector('#rank .section h2');if(title)title.textContent=p==='year'?'Ranking Geral 2026':`Ranking ${MONTH_NAMES[Number(p)]} 2026`;$('rankSummary').innerHTML=[stat('Profissionais',num(a.length)),stat('Casais',num(tot.couples)),stat('Vendas',num(tot.sales)),stat('VGV Ativo',money(tot.vgv)),stat('VGV Geral',money(tot.vgv_general)),stat('Cancelamentos',num(tot.cancelled)),stat('NoTour',num(tot.notour))].join('');$('rankBody').innerHTML=a.map((x,i)=>`<tr><td><b>${i+1}º</b></td><td><span class="nameLink" data-name="${esc(x.name)}">${esc(x.name)}</span><div class="tiny">${esc(x.group||'')}</div></td><td><span class="pill ${x.active?'':'off'}">${x.active?'ATIVO':'INATIVO'}</span></td><td>${num(x.couples)}</td><td>${num(x.q)}</td><td>${num(x.nq)}</td><td>${num(x.sales)}</td><td>${conv(x)}</td><td>${money(x.vgv_general)}</td><td><b>${money(x.vgv)}</b></td><td>${money(x.gift)}</td><td>${money(x.couples?x.gift/x.couples:0,2)}</td><td>${num(x.notour)}</td><td>${num(x.cancelled)}</td></tr>`).join('');document.querySelectorAll('#rank .nameLink').forEach(el=>el.onclick=()=>{$('profilePerson').value=el.dataset.name;show('profile')})}
['rankMetric','rankStatus','rankPeriod'].forEach(id=>$(id)&&($(id).onchange=renderRank));if($('rankSearch'))$('rankSearch').oninput=renderRank;

function renderCalendar(){const mm=Array.from({length:9},(_,i)=>({month:i+1,...monthTotal(i+1)}));$('monthGrid').innerHTML=mm.map(x=>`<div class="card"><div class="label">${MONTH_NAMES[x.month]} 2026</div><b style="font-size:22px;display:block;margin-top:6px">${money(x.vgv)}</b><div class="tiny">VGV ativo</div><div class="monthData"><div><span class="label">Casais</span><b>${num(x.couples)}</b></div><div><span class="label">Vendas</span><b>${num(x.sales)}</b></div><div><span class="label">Conversão</span><b>${conv(x)}</b></div><div><span class="label">VGV Geral</span><b>${money(x.vgv_general)}</b></div><div><span class="label">Q / NQ</span><b>${num(x.q)} / ${num(x.nq)}</b></div><div><span class="label">Cancel.</span><b>${num(x.cancelled)}</b></div></div></div>`).join('')}

function setupSelects(){const sel=$('profilePerson'),names=allPeople();sel.innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');sel.value=names.find(n=>effectivePerson(n).active)||names[0]||'';sel.onchange=renderProfile}
function renderProfile(){const n=$('profilePerson').value||allPeople()[0],p=effectivePerson(n),active=allPeople().map(effectivePerson).filter(x=>x.active).sort((a,b)=>b.vgv-a.vgv),pos=active.findIndex(x=>x.name===n)+1;$('profileName').textContent=n;$('profileRole').textContent=`${p.role||'CAPTADOR'} • ${p.group||'A DEFINIR'} • ${p.active?'ATIVO':'INATIVO'}`;$('profileRank').textContent=p.active&&pos?`#${pos}`:'—';$('profileStats').innerHTML=[stat('Casais',num(p.couples),`${num(p.q)} Q • ${num(p.nq)} NQ`),stat('Vendas',num(p.sales),`Conversão ${conv(p)}`),stat('VGV Ativo',money(p.vgv)),stat('VGV Geral',money(p.vgv_general)),stat('Ticket',money(p.sales?p.vgv/p.sales:0)),stat('Cancelamentos',num(p.cancelled)),stat('NoTour',num(p.notour)),stat('Brindes',money(p.gift),`Custo/casal ${money(p.couples?p.gift/p.couples:0,2)}`)].join('');const arr=Array.from({length:9},(_,i)=>({month:i+1,...personMonth(n,i+1)})),max=Math.max(1,...arr.map(x=>x.vgv));$('profileMonths').innerHTML=`<div class="bars">${arr.map(x=>`<div class="barrow"><span>${MONTH_NAMES[x.month]}</span><div class="bartrack"><div class="barfill" style="width:${x.vgv/max*100}%"></div></div><b>${money(x.vgv)}</b></div>`).join('')}</div><div class="tablewrap" style="margin-top:12px"><table class="table" style="min-width:650px"><thead><tr><th>Mês</th><th>Casais</th><th>Vendas</th><th>Conversão</th><th>VGV</th><th>Cancel.</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${MONTH_NAMES[x.month]}</td><td>${num(x.couples)}</td><td>${num(x.sales)}</td><td>${conv(x)}</td><td>${money(x.vgv)}</td><td>${num(x.cancelled)}</td></tr>`).join('')}</tbody></table></div>`}

function activeSepRanking(){return allPeople().map(n=>({name:n,...personMonth(n,9),active:effectivePerson(n).active})).filter(x=>x.active).sort((a,b)=>b.vgv-a.vgv)}
function renderSeptember(){const s=sepTotal(),m=currentMeta(),days=Math.max(1,Number(String(m.through).slice(8,10))||1),rem=Math.max(1,30-days);$('sepStats').innerHTML=[stat('Casais',num(s.couples),`${pct(s.couples,METAS.couples)} da meta`),stat('Vendas',num(s.sales),`${pct(s.sales,METAS.sales)} da meta`),stat('VGV Ativo',money(s.vgv),`${pct(s.vgv,METAS.vgv)} da meta`),stat('VGV Geral',money(s.vgv_general)),stat('Conversão',conv(s)),stat('Q / NQ',`${num(s.q)} / ${num(s.nq)}`),stat('Cancelamentos',num(s.cancelled)),stat('NoTour',num(s.notour))].join('');const targets=[['Casais',s.couples,METAS.couples,s.couples/days*30,false],['Vendas',s.sales,METAS.sales,s.sales/days*30,false],['VGV',s.vgv,METAS.vgv,s.vgv/days*30,true]];$('sepTargets').innerHTML=targets.map(x=>progressStat(...x)).join('')+`<div class="insight" style="margin-top:8px"><b>Necessário por dia</b>${money(Math.max(0,METAS.vgv-s.vgv)/rem)} VGV • ${(Math.max(0,METAS.couples-s.couples)/rem).toFixed(1)} casais • ${(Math.max(0,METAS.sales-s.sales)/rem).toFixed(1)} vendas</div>`;$('sepTop').innerHTML=activeSepRanking().slice(0,8).map((x,i)=>`<div class="member"><b>${i+1}º ${esc(x.name)}</b><span class="tiny">${num(x.couples)} casais • ${num(x.sales)} vendas • ${money(x.vgv)}</span></div>`).join('');const daysRows=hasOfficialRows()?Object.entries(OFFICIAL_ROWS.filter(r=>String(r.date).startsWith('2026-09')).reduce((m,r)=>{const d=Number(r.date.slice(8,10));m[d]||(m[d]={day:d,...blank()});plus(m[d],r);return m},{})).map(([,v])=>v).sort((a,b)=>a.day-b.day):SEPTEMBER_DAYS;$('dayBody').innerHTML=daysRows.map(x=>`<tr><td>${String(x.day).padStart(2,'0')}/09</td><td>${num(x.couples)}</td><td>${num(x.q)}</td><td>${num(x.nq)}</td><td>${num(x.sales)}</td><td>${money(x.vgv)}</td><td>${money(x.vgv_general)}</td><td>${num(x.notour)}</td><td>${money(x.gift)}</td></tr>`).join('')}

function renderTeams(){const groups=[...new Set(allPeople().filter(n=>effectivePerson(n).active).map(n=>effectivePerson(n).group||'A DEFINIR'))].sort();$('teamGrid').innerHTML=groups.map(g=>{const members=allPeople().filter(n=>effectivePerson(n).active&&(effectivePerson(n).group||'A DEFINIR')===g),a=members.reduce((z,n)=>plus(z,personMonth(n,9)),blank());return `<div class="card"><div class="label">Equipe</div><h2>${esc(g)}</h2><div class="stats" style="grid-template-columns:repeat(3,1fr)">${stat('Casais',num(a.couples))}${stat('Vendas',num(a.sales))}${stat('VGV',money(a.vgv))}</div><div style="margin-top:10px">${members.map(n=>{const s=personMonth(n,9);return `<div class="member"><b>${esc(n)}</b><span class="tiny">${num(s.couples)} casais • ${num(s.sales)} vendas • ${money(s.vgv)}</span></div>`}).join('')}</div></div>`}).join('')}
function renderInactive(){const m=currentMeta();$('inactiveBody').innerHTML=allPeople().map(effectivePerson).filter(x=>!x.active).sort((a,b)=>b.vgv_general-a.vgv_general).map(x=>`<tr><td>${esc(x.name)}</td><td>${num(x.couples)}</td><td>${num(x.sales)}</td><td>${money(x.vgv_general)}</td><td>${money(x.vgv)}</td><td>${String(m.through).split('-').reverse().join('/')}</td></tr>`).join('')}
function refreshAll(){renderHeader();renderDashboard();renderRank();renderCalendar();renderProfile();renderSeptember();renderTeams();renderInactive();window.renderCaptain?.();window.TXAlerts?.render?.()}

window.TX={
  getRows:()=>hasOfficialRows()?[...OFFICIAL_ROWS]:[],getMeta:()=>currentMeta(),hasImported:hasOfficialRows,
  reloadOfficial(){OFFICIAL_ROWS=readJSON(OFFICIAL_STORE,[]);OFFICIAL_INFO=readJSON(OFFICIAL_META,null);setupSelects();refreshAll();window.dispatchEvent(new CustomEvent('targetx:data-updated'))},
  clearImported(){localStorage.removeItem(OFFICIAL_STORE);localStorage.removeItem(OFFICIAL_META);OFFICIAL_ROWS=[];OFFICIAL_INFO=null;setupSelects();refreshAll()},
  stores:{rows:OFFICIAL_STORE,meta:OFFICIAL_META}
};

setupSelects();refreshAll();