const $=id=>document.getElementById(id), money=(v,d=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:d}).format(v||0), num=v=>new Intl.NumberFormat('pt-BR').format(Math.round(v||0)), pct=(a,b)=>b?((a/b)*100).toFixed(1)+'%':'0%';
const METAS={couples:370,sales:101,vgv:8500000}, MONTH_NAMES=['','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
let launches=JSON.parse(localStorage.getItem('tx_launches_v40')||'[]');let notes=JSON.parse(localStorage.getItem('tx_notes_v40')||'[]');launches=launches.filter(x=>!x.date||x.date>DATA_META.through);localStorage.setItem('tx_launches_v40',JSON.stringify(launches));
function saveState(){localStorage.setItem('tx_launches_v40',JSON.stringify(launches));localStorage.setItem('tx_notes_v40',JSON.stringify(notes))}
function clone(o){return JSON.parse(JSON.stringify(o))}function blank(){return {couples:0,q:0,nq:0,sales:0,cancelled:0,vgv:0,vgv_general:0,gift:0,notour:0,attendances:0}}function convBase(x){return Math.max(0,(x.couples||0)-(x.notour||0))}function conv(x){return pct(x.sales,convBase(x))}function baseDay(){return Number(String(DATA_META.through||'').slice(8,10))||1}
function plus(a,b){for(const k of Object.keys(blank()))a[k]=(a[k]||0)+(Number(b[k])||0);return a}
function launchAgg(filter=()=>true){let a=blank();launches.filter(x=>(!x.date||x.date>DATA_META.through)&&filter(x)).forEach(x=>plus(a,x));return a}
function baseTotal(){return HIST.reduce((a,x)=>plus(a,x),blank())}function annualTotal(){return plus(baseTotal(),launchAgg())}
function baseSep(){return clone(MONTHS.find(x=>x.month===9)||blank())}function sepTotal(){return plus(baseSep(),launchAgg(x=>String(x.date||'').startsWith('2026-09')))}
function effectivePerson(name){let p=clone(HIST.find(x=>x.name===name)||{name,...blank(),active:true,group:'A DEFINIR',role:'CAPTADOR'});launches.filter(x=>x.person===name&&(!x.date||x.date>DATA_META.through)).forEach(x=>plus(p,x));return p}
function personMonth(name,m){let a=clone((PERSON_MONTHS[name]&&PERSON_MONTHS[name][String(m)])||blank());launches.filter(x=>x.person===name&&(!x.date||x.date>DATA_META.through)&&Number((x.date||'').slice(5,7))===m).forEach(x=>plus(a,x));return a}
function allPeople(){let set=new Set(HIST.map(x=>x.name));launches.filter(x=>!x.date||x.date>DATA_META.through).forEach(x=>set.add(x.person));return [...set].sort()}
function stat(label,value,small=''){return `<div class="card stat"><span class="label">${label}</span><b>${value}</b>${small?`<small>${small}</small>`:''}</div>`}
function show(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===p));if(p==='dashboard')renderDashboard();if(p==='rank')renderRank();if(p==='calendar')renderCalendar();if(p==='profile')renderProfile();if(p==='september')renderSeptember();if(p==='diary')renderDiary();if(p==='launch')renderLaunches();if(p==='teams')renderTeams();if(p==='inactive')renderInactive()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.page));
function renderDashboard(){let a=annualTotal(),s=sepTotal(),days=Math.max(baseDay(),...launches.filter(x=>(!x.date||x.date>DATA_META.through)&&String(x.date).startsWith('2026-09')).map(x=>Number(String(x.date).slice(8,10))||0)),remain=Math.max(1,30-days);$('headerMeta').textContent=`Base ${DATA_META.from.split('-').reverse().join('/')} até ${DATA_META.through.split('-').reverse().join('/')} • ${num(DATA_META.records)} registros`;$('annualStats').innerHTML=[stat('Casais',num(a.couples),`${num(a.q)} Q • ${num(a.nq)} NQ`),stat('Vendas ativas',num(a.sales),`Conversão ${conv(a)} • NoTour fora da conversão`),stat('VGV Ativo',money(a.vgv),`Ticket ${money(a.sales?a.vgv/a.sales:0)}`),stat('VGV Geral',money(a.vgv_general)),stat('NoTour',num(a.notour)),stat('Brindes',money(a.gift),`Custo/casal ${money(a.couples?a.gift/a.couples:0,2)}`)].join('');let proj={couples:s.couples/days*30,sales:s.sales/days*30,vgv:s.vgv/days*30};$('sepProgress').innerHTML=[progressStat('Casais',s.couples,METAS.couples,proj.couples),progressStat('Vendas',s.sales,METAS.sales,proj.sales),progressStat('VGV Ativo',s.vgv,METAS.vgv,proj.vgv,true),stat('Necessário/dia',money(Math.max(0,METAS.vgv-s.vgv)/remain),`${Math.max(0,(METAS.couples-s.couples)/remain).toFixed(1)} casais • ${Math.max(0,(METAS.sales-s.sales)/remain).toFixed(1)} vendas`)].join('');let mm=MONTHS.map(x=>{let a=clone(x);if(x.month===9)launches.filter(l=>(!l.date||l.date>DATA_META.through)&&String(l.date).startsWith('2026-09')).forEach(l=>plus(a,l));return a}),max=Math.max(...mm.map(x=>x.vgv));$('vgvBars').innerHTML=mm.map(x=>`<div class="barrow"><span>${MONTH_NAMES[x.month]}</span><div class="bartrack"><div class="barfill" style="width:${max?x.vgv/max*100:0}%"></div></div><b>${money(x.vgv)}</b></div>`).join('');let best=[...mm].sort((x,y)=>y.vgv-x.vgv)[0],rankSep=activeSepRanking(),leader=rankSep[0];$('insights').innerHTML=`<div class="insight"><b>Melhor mês do ano</b>${MONTH_NAMES[best.month]} • ${money(best.vgv)} VGV ativo • ${num(best.sales)} vendas.</div><div class="insight"><b>Projeção de setembro</b>${money(proj.vgv)} em VGV, ${Math.round(proj.sales)} vendas e ${Math.round(proj.couples)} casais.</div><div class="insight"><b>Líder de setembro por VGV</b>${leader?leader.name+' • '+money(leader.vgv):'Sem dados'}.</div><div class="insight"><b>Sinal de gestão</b>${proj.vgv>=METAS.vgv?'<span class="green">VGV acima do ritmo da meta.</span>':'<span class="amber">VGV projetado abaixo da meta; precisa elevar o valor diário.</span>'}</div>`}
function progressStat(label,actual,target,projection,isMoney=false){let pc=Math.min(100,target?actual/target*100:0),cls=projection>=target?'':'amber';return `<div class="card stat"><span class="label">${label}</span><b>${isMoney?money(actual):num(actual)} <span class="tiny">/ ${isMoney?money(target):num(target)}</span></b><div class="progress ${cls}"><i style="width:${pc}%"></i></div><small>Projeção: ${isMoney?money(projection):num(projection)} • ${pc.toFixed(1)}%</small></div>`}
function filteredRank(){let arr=allPeople().map(effectivePerson),q=$('rankSearch').value.trim().toUpperCase(),st=$('rankStatus').value,k=$('rankMetric').value;if(q)arr=arr.filter(x=>x.name.includes(q));if(st==='active')arr=arr.filter(x=>x.active);if(st==='inactive')arr=arr.filter(x=>!x.active);arr.sort((x,y)=>k==='conversion'?(y.sales/(convBase(y)||1))-(x.sales/(convBase(x)||1)):(y[k]||0)-(x[k]||0));return arr}
function renderRank(){let a=filteredRank(),tot=a.reduce((z,x)=>plus(z,x),blank());$('rankSummary').innerHTML=[stat('Profissionais',num(a.length)),stat('Casais',num(tot.couples)),stat('Vendas',num(tot.sales)),stat('VGV Ativo',money(tot.vgv)),stat('VGV Geral',money(tot.vgv_general))].join('');$('rankBody').innerHTML=a.map((x,i)=>`<tr><td><b>${i+1}º</b></td><td><span class="nameLink" data-name="${x.name.replace(/"/g,'&quot;')}">${x.name}</span><div class="tiny">${x.group||''}</div></td><td><span class="pill ${x.active?'':'off'}">${x.active?'ATIVO':'INATIVO'}</span></td><td>${num(x.couples)}</td><td>${num(x.q)}</td><td>${num(x.nq)}</td><td>${num(x.sales)}</td><td>${conv(x)}</td><td>${money(x.vgv_general)}</td><td><b>${money(x.vgv)}</b></td><td>${money(x.gift)}</td><td>${money(x.couples?x.gift/x.couples:0,2)}</td><td>${num(x.notour)}</td><td>${num(x.cancelled)}</td></tr>`).join('');document.querySelectorAll('.nameLink').forEach(el=>el.onclick=()=>{profilePerson.value=el.dataset.name;show('profile')})}
$('rankMetric').onchange=$('rankStatus').onchange=$('rankSearch').oninput=renderRank;
function renderCalendar(){let mm=MONTHS.map(x=>{let a=clone(x);if(x.month===9)launches.filter(l=>(!l.date||l.date>DATA_META.through)&&String(l.date).startsWith('2026-09')).forEach(l=>plus(a,l));return a});$('monthGrid').innerHTML=mm.map(x=>`<div class="card"><div class="label">${MONTH_NAMES[x.month]} 2026</div><b style="font-size:22px;display:block;margin-top:6px">${money(x.vgv)}</b><div class="tiny">VGV ativo</div><div class="monthData"><div><span class="label">Casais</span><b>${num(x.couples)}</b></div><div><span class="label">Vendas</span><b>${num(x.sales)}</b></div><div><span class="label">Conversão</span><b>${conv(x)}</b></div><div><span class="label">VGV Geral</span><b>${money(x.vgv_general)}</b></div><div><span class="label">Q / NQ</span><b>${num(x.q)} / ${num(x.nq)}</b></div><div><span class="label">NoTour</span><b>${num(x.notour)}</b></div></div></div>`).join('')}
function setupSelects(){let names=allPeople();profilePerson.innerHTML=names.map(n=>`<option>${n}</option>`).join('');launchPerson.innerHTML=HIST.filter(x=>x.active).sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<option>${x.name}</option>`).join('');profilePerson.value=HIST.find(x=>x.active)?.name||names[0];noteDate.value=new Date().toISOString().slice(0,10);launchDate.value='2026-09-08'}
function renderProfile(){let n=profilePerson.value||allPeople()[0],p=effectivePerson(n),activeSorted=allPeople().map(effectivePerson).filter(x=>x.active).sort((a,b)=>b.vgv-a.vgv),pos=activeSorted.findIndex(x=>x.name===n)+1;$('profileName').textContent=n;$('profileRole').textContent=`${p.role||'CAPTADOR'} • ${p.group||'A DEFINIR'} • ${p.active?'ATIVO':'INATIVO'}`;$('profileRank').textContent=p.active&&pos?`#${pos}`:'—';$('profileStats').innerHTML=[stat('Casais',num(p.couples),`${num(p.q)} Q • ${num(p.nq)} NQ`),stat('Vendas',num(p.sales),`Conversão ${conv(p)} • NoTour fora da conversão`),stat('VGV Ativo',money(p.vgv)),stat('VGV Geral',money(p.vgv_general)),stat('Ticket',money(p.sales?p.vgv/p.sales:0)),stat('NoTour',num(p.notour)),stat('Brindes',money(p.gift),`Custo/casal ${money(p.couples?p.gift/p.couples:0,2)}`)].join('');let arr=[];for(let m=1;m<=9;m++)arr.push({month:m,...personMonth(n,m)});let max=Math.max(1,...arr.map(x=>x.vgv));$('profileMonths').innerHTML=`<div class="bars">${arr.map(x=>`<div class="barrow"><span>${MONTH_NAMES[x.month]}</span><div class="bartrack"><div class="barfill" style="width:${x.vgv/max*100}%"></div></div><b>${money(x.vgv)}</b></div>`).join('')}</div><div class="tablewrap" style="margin-top:12px"><table class="table" style="min-width:650px"><thead><tr><th>Mês</th><th>Casais</th><th>Vendas</th><th>Conversão</th><th>VGV</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${MONTH_NAMES[x.month]}</td><td>${num(x.couples)}</td><td>${num(x.sales)}</td><td>${conv(x)}</td><td>${money(x.vgv)}</td></tr>`).join('')}</tbody></table></div>`;renderProfileNotes()}
profilePerson.onchange=renderProfile;
function renderProfileNotes(){let n=profilePerson.value,list=notes.filter(x=>x.person===n).sort((a,b)=>(b.date||'').localeCompare(a.date||''));$('profileNotes').innerHTML=list.length?list.map(x=>`<div class="note"><div class="noteTop"><div><b>${x.type} • ${(x.date||'').split('-').reverse().join('/')}</b><div class="tiny">${n}</div></div><button data-note="${x.id}">Excluir</button></div><div style="margin-top:7px">${escapeHtml(x.text)}</div></div>`).join(''):'<div class="empty">Nenhuma anotação para este profissional.</div>';document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{notes=notes.filter(x=>x.id!==b.dataset.note);saveState();renderProfileNotes()})}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('saveNote').onclick=()=>{let t=noteText.value.trim();if(!t)return;notes.push({id:String(Date.now()),person:profilePerson.value,date:noteDate.value||new Date().toISOString().slice(0,10),type:noteType.value,text:t});noteText.value='';saveState();renderProfileNotes()};
function activeSepRanking(){return HIST.filter(x=>x.active).map(x=>({name:x.name,...personMonth(x.name,9)})).sort((a,b)=>b.vgv-a.vgv)}
function renderSeptember(){let s=sepTotal(),days=Math.max(baseDay(),...launches.filter(x=>(!x.date||x.date>DATA_META.through)&&String(x.date).startsWith('2026-09')).map(x=>Number(String(x.date).slice(8,10))||0));$('sepStats').innerHTML=[stat('Casais',num(s.couples),`${pct(s.couples,METAS.couples)} da meta`),stat('Vendas',num(s.sales),`${pct(s.sales,METAS.sales)} da meta`),stat('VGV Ativo',money(s.vgv),`${pct(s.vgv,METAS.vgv)} da meta`),stat('VGV Geral',money(s.vgv_general)),stat('Conversão',conv(s),'NoTour fora da conversão'),stat('Q / NQ',`${num(s.q)} / ${num(s.nq)}`),stat('NoTour',num(s.notour)),stat('Brindes',money(s.gift))].join('');let rem=Math.max(1,30-days);let targets=[['Casais',s.couples,METAS.couples,s.couples/days*30,false],['Vendas',s.sales,METAS.sales,s.sales/days*30,false],['VGV',s.vgv,METAS.vgv,s.vgv/days*30,true]];$('sepTargets').innerHTML=targets.map(([l,a,t,p,m])=>`${progressStat(l,a,t,p,m)}<div class="tiny" style="margin:4px 4px 12px">Faltam ${m?money(Math.max(0,t-a)):num(Math.max(0,t-a))} • necessário/dia ${m?money(Math.max(0,t-a)/rem):((Math.max(0,t-a)/rem).toFixed(1))}</div>`).join('');$('sepTop').innerHTML=activeSepRanking().slice(0,8).map((x,i)=>`<div class="member"><b>${i+1}º ${x.name}</b><span class="tiny">${num(x.couples)} casais • ${num(x.sales)} vendas • ${money(x.vgv)}</span></div>`).join('');let dayMap={};SEPTEMBER_DAYS.forEach(x=>dayMap[x.day]=clone(x));launches.filter(x=>(!x.date||x.date>DATA_META.through)&&String(x.date).startsWith('2026-09')).forEach(l=>{let d=Number(String(l.date).slice(8,10));dayMap[d]||(dayMap[d]={day:d,...blank()});plus(dayMap[d],l)});$('dayBody').innerHTML=Object.values(dayMap).sort((a,b)=>a.day-b.day).map(x=>`<tr><td><b>${String(x.day).padStart(2,'0')}/09</b></td><td>${num(x.couples)}</td><td>${num(x.q)}</td><td>${num(x.nq)}</td><td>${num(x.sales)}</td><td>${money(x.vgv)}</td><td>${money(x.vgv_general)}</td><td>${num(x.notour)}</td><td>${money(x.gift)}</td></tr>`).join('')}
function renderDiary(){let q=$('diarySearch').value.trim().toUpperCase(),list=[...notes].sort((a,b)=>(b.date||'').localeCompare(a.date||''));if(q)list=list.filter(x=>(x.person+' '+x.type+' '+x.text).toUpperCase().includes(q));$('diaryList').innerHTML=list.length?list.map(x=>`<div class="card note"><b>${x.person}</b><div class="tiny">${x.type} • ${(x.date||'').split('-').reverse().join('/')}</div><div style="margin-top:7px">${escapeHtml(x.text)}</div></div>`).join(''):'<div class="card empty">Ainda não há anotações salvas.</div>'}
$('diarySearch').oninput=renderDiary;
$('launchBtn').onclick=()=>{let date=launchDate.value,person=launchPerson.value;if(!date||date<=DATA_META.through||!person)return alert(`Use uma data após ${DATA_META.through.split('-').reverse().join('/')}.`);let x={id:String(Date.now()),date,person,couples:+launchCouples.value||0,sales:+launchSales.value||0,vgv:+launchVgv.value||0,vgv_general:+launchVgvGeneral.value||(+launchVgv.value||0),q:+launchQ.value||0,nq:+launchNq.value||0,notour:+launchNotour.value||0,gift:+launchGift.value||0,cancelled:0,attendances:(+launchCouples.value||0)};launches.push(x);saveState();['launchCouples','launchSales','launchVgv','launchVgvGeneral','launchQ','launchNq','launchNotour','launchGift'].forEach(id=>$(id).value='');renderLaunches()};
function renderLaunches(){$('launchBody').innerHTML=launches.filter(x=>!x.date||x.date>DATA_META.through).length?[...launches].filter(x=>!x.date||x.date>DATA_META.through).sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${x.date.split('-').reverse().join('/')}</td><td>${x.person}</td><td>${num(x.couples)}</td><td>${num(x.sales)}</td><td>${money(x.vgv)}</td><td>${money(x.vgv_general)}</td><td>${num(x.q)}</td><td>${num(x.nq)}</td><td>${num(x.notour)}</td><td><button data-del-launch="${x.id}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="10" class="empty">Nenhum lançamento manual ainda.</td></tr>';document.querySelectorAll('[data-del-launch]').forEach(b=>b.onclick=()=>{launches=launches.filter(x=>x.id!==b.dataset.delLaunch);saveState();renderLaunches()})}
function renderTeams(){let groups=['FELIPE','CLACION','A DEFINIR'];$('teamGrid').innerHTML=groups.map(g=>{let members=HIST.filter(x=>x.active&&(x.group||'A DEFINIR')===g),agg=members.reduce((a,p)=>plus(a,personMonth(p.name,9)),blank());return `<div class="card"><div class="label">Equipe</div><h2>${g}</h2><div class="stats" style="grid-template-columns:repeat(3,1fr)">${stat('Casais',num(agg.couples))}${stat('Vendas',num(agg.sales))}${stat('VGV',money(agg.vgv))}</div><div style="margin-top:10px">${members.map(p=>{let s=personMonth(p.name,9);return `<div class="member"><b>${p.name}</b><span class="tiny">${num(s.couples)} casais • ${num(s.sales)} vendas • ${money(s.vgv)}</span></div>`}).join('')}</div></div>`}).join('')}
function renderInactive(){let a=HIST.filter(x=>!x.active).sort((x,y)=>y.vgv_general-x.vgv_general),base=DATA_META.through.split('-').reverse().join('/');$('inactiveBody').innerHTML=a.map(x=>`<tr><td><span class="nameLink" data-inactive="${x.name.replace(/"/g,'&quot;')}">${x.name}</span></td><td>${num(x.couples)}</td><td>${num(x.sales)}</td><td>${money(x.vgv_general)}</td><td>${money(x.vgv)}</td><td>${base}</td></tr>`).join('');document.querySelectorAll('[data-inactive]').forEach(el=>el.onclick=()=>{profilePerson.value=el.dataset.inactive;show('profile')})}
setupSelects();renderDashboard();renderRank();renderCalendar();renderProfile();renderLaunches();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=48').catch(()=>{});
setTimeout(()=>{launches=launches.filter(x=>!x.date||x.date>DATA_META.through);saveState();METAS.couples=370;METAS.sales=101;METAS.vgv=8500000;const cards=document.querySelectorAll('#dashboard .hero .card');if(cards[1]){const line=cards[1].querySelector('b');if(line)line.textContent='101 vendas • 370 casais';}try{renderDashboard();renderRank();renderCalendar();renderProfile();renderSeptember();renderTeams();renderLaunches();if(window.renderCaptain)renderCaptain();}catch(e){console.warn('TARGET X base guard',e)}},0);