// TARGET X — Perfil do Cliente / inteligência comercial
(function(){
  if(window.__txClientProfileLoaded)return;window.__txClientProfileLoaded=true;
  const STORE='tx_client_profile_v1',META='tx_client_profile_meta_v1';
  const MONTHS=['','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
  const css=document.createElement('style');css.textContent=`
  .cpFilters{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:8px}.cpGrid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.cpList{display:grid;gap:7px}.cpRow{display:grid;grid-template-columns:minmax(0,1fr) 75px 70px;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid #14271f}.cpRow:last-child{border-bottom:0}.cpBar{height:7px;background:#102019;border-radius:99px;overflow:hidden;margin-top:5px}.cpBar i{display:block;height:100%;background:var(--green);border-radius:99px}.cpHero{display:grid;grid-template-columns:1.3fr .7fr;gap:11px}.cpBuyer{font-size:clamp(28px,5vw,48px);font-weight:1000;line-height:1;color:var(--green);margin:8px 0}.cpTag{display:inline-block;padding:6px 8px;border:1px solid var(--line);border-radius:99px;margin:3px 4px 0 0;font-size:10px}.cpTable{width:100%;border-collapse:collapse}.cpTable th,.cpTable td{padding:8px;border-bottom:1px solid #14271f;text-align:left}.cpTable th{font-size:9px;color:var(--muted);text-transform:uppercase}.cpTable td:nth-child(n+2),.cpTable th:nth-child(n+2){text-align:right}.cpHint{padding:16px;border:1px dashed #315c47;border-radius:14px;background:#06100b}.cpHint b{display:block;margin-bottom:5px}.cpGood{color:var(--green)}
  @media(max-width:900px){.cpGrid,.cpHero{grid-template-columns:1fr}.cpFilters{grid-template-columns:1fr 1fr}}@media(max-width:560px){.cpFilters{grid-template-columns:1fr}.cpRow{grid-template-columns:minmax(0,1fr) 58px 55px}}
  `;document.head.appendChild(css);

  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
  const n=v=>{if(typeof v==='number')return isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/R\$|\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0};
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
  const num=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(Math.round(v||0));
  const pct=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'0%';
  const get=(row,...names)=>{const ks=Object.keys(row);for(const name of names){const target=norm(name),k=ks.find(k=>norm(k)===target);if(k!==undefined)return row[k]}return ''};
  function ymd(v){if(!v)return '';if(typeof v==='number'&&window.XLSX?.SSF?.parse_date_code){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`;}let s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);if(!isNaN(d))return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return ''}
  function sold(status){return /\bATIVO\b/.test(norm(status))}
  function cleanRel(v){const x=norm(v);if(!x)return 'NÃO INFORMADO';if(x==='UNIAO ESTAVEL')return 'UNIÃO ESTÁVEL';if(x==='CASADO'||x==='CASADA')return 'CASADO';if(x==='NOIVOS'||x==='NOIVO'||x==='NOIVA')return 'NOIVOS';if(x==='NAMORADOS'||x==='NAMORADO'||x==='NAMORADA')return 'NAMORADOS';if(x==='SOLTEIRO'||x==='SOLTEIRA')return 'SOLTEIRO';return String(v).trim().toUpperCase()}
  function cleanHome(v){const x=norm(v);if(!x||x==='NAO SELECIONADO')return 'NÃO INFORMADO';if(x.includes('VERIFICADO')||x.includes('PROPRIA')||x==='SIM')return 'CASA PRÓPRIA';if(x==='NAO'||x.includes('ALUG'))return 'SEM CASA PRÓPRIA';return String(v).trim().toUpperCase()}
  function qual(v){const x=norm(v);if(/^Q\b/.test(x)||x.includes('PERFIL QUALIFICADO'))return 'Q';if(/^NQ\b/.test(x))return 'NQ';return '—'}
  function compact(row){const date=ymd(get(row,'Data de atendimento','Data'));if(!date)return null;const income=n(get(row,'Renda','Renda Bruta','Renda familiar'));const car=String(get(row,'Carro 1','Carro','Veículo','Veiculo')||'').trim().toUpperCase();const cy=Math.round(n(get(row,'Ano carro 1','Ano carro','Ano do carro')))||0;const home=cleanHome(get(row,'Residência própria','Residencia propria','Casa própria','Casa propria'));const rel=cleanRel(get(row,'Tipo de relacionamento','Relacionamento','Estado civil'));const p1=String(get(row,'Profissão 1','Profissao 1','Profissão','Profissao')||'').trim();const p2=String(get(row,'Profissão 2','Profissao 2')||'').trim();const city=String(get(row,'Cidade')||'').trim();const uf=String(get(row,'UF','Estado')||'').trim().toUpperCase();const a1=Math.round(n(get(row,'Idade 1','Idade')))||0,a2=Math.round(n(get(row,'Idade 2')))||0;const q=qual(get(row,'Qualificação','Qualificacao','Motivo de qualificação','Motivo de qualificacao'));const isBuyer=sold(get(row,'Status do contrato','Status contrato'))?1:0;const value=n(get(row,'Valor vendido','VGV','VGV Geral'));return [date,income,car,cy,home,rel,p1,p2,city,uf,a1,a2,q,isBuyer,value]}
  const readRows=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return []}};
  function saveRows(rows,file){try{localStorage.setItem(STORE,JSON.stringify(rows));const dates=rows.map(r=>r[0]).filter(Boolean).sort();localStorage.setItem(META,JSON.stringify({file:file||'',rows:rows.length,from:dates[0]||'',through:dates.at(-1)||'',when:new Date().toISOString()}));return true}catch(e){console.warn(e);return false}}
  const meta=()=>{try{return JSON.parse(localStorage.getItem(META)||'null')}catch{return null}};
  async function ensureXlsx(){if(window.XLSX)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  async function importClientFile(file){if(!file)return;const status=document.getElementById('cpDataStatus');if(status)status.textContent='Lendo perfil dos clientes...';try{await ensureXlsx();const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:false});let rows=[];wb.SheetNames.forEach(sn=>{XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:'',raw:true}).forEach(r=>{const c=compact(r);if(c)rows.push(c)})});if(!rows.length)throw new Error('Não encontrei registros de clientes na planilha.');const ok=saveRows(rows,file.name);if(!ok)throw new Error('O navegador não conseguiu salvar os dados do perfil.');window.dispatchEvent(new CustomEvent('tx-client-data-updated',{detail:{rows:rows.length,file:file.name}}));renderClientProfile();const up=document.getElementById('txUploadStatus');if(up&&rows.length){const base=window.DATA_META?.through?.split('-').reverse().join('/')||'';up.innerHTML=`<span class="green">✓ Perfil Cliente atualizado.</span> ${num(rows.length)} atendimentos lidos${base?` • base de performance até ${base}`:''}.`;}}
    catch(e){console.warn(e);if(status)status.innerHTML=`<span class="red">${e.message||e}</span>`}}
  }

  function mountUploadHook(){const fi=document.getElementById('txSheetFile');if(!fi||fi.dataset.cpHook)return false;fi.dataset.cpHook='1';fi.addEventListener('change',()=>{const f=fi.files?.[0];if(f)importClientFile(f)});return true}
  let hookTries=0;const hookTimer=setInterval(()=>{if(mountUploadHook()||++hookTries>30)clearInterval(hookTimer)},300);

  function mountUI(){const nav=document.querySelector('.tabs');if(!nav)return;const professional=[...nav.querySelectorAll('.tab')].find(b=>b.dataset.page==='profile');if(professional)professional.textContent='Profissional';if(!document.querySelector('[data-page="clientprofile"]')){const b=document.createElement('button');b.className='tab';b.dataset.page='clientprofile';b.textContent='Perfil Cliente';nav.insertBefore(b,professional||nav.children[3]||null);b.onclick=()=>{if(typeof show==='function')show('clientprofile');renderClientProfile()}}if(!document.getElementById('clientprofile')){const page=document.createElement('section');page.className='page';page.id='clientprofile';page.innerHTML=`
    <div class="section"><div><h2>Perfil do Cliente</h2><div class="meta">Quem atendemos e, principalmente, quem compra.</div></div><div class="meta" id="cpDataStatus"></div></div>
    <div class="card"><div class="cpFilters"><select id="cpPeriod"><option value="all">Ano 2026</option></select><select id="cpScope"><option value="all">Todos os atendidos</option><option value="buyers">Somente compradores</option></select><select id="cpQual"><option value="all">Q + NQ</option><option value="Q">Somente Q</option><option value="NQ">Somente NQ</option></select></div></div>
    <div id="cpNoData" class="cpHint" style="margin-top:11px;display:none"><b>Carregue a planilha oficial uma vez.</b>O TARGET X vai ler renda, carro, residência própria, relacionamento, profissões, idade, cidade e compradores. Depois o relatório fica salvo neste navegador.</div>
    <div id="cpBody">
      <div class="section"><h2>Visão do perfil</h2><span class="meta" id="cpRange"></span></div><div class="stats" id="cpStats"></div>
      <div class="section"><h2>Quem compra</h2><span class="meta">raio-x dos compradores</span></div><div class="cpHero"><div class="card"><div class="label">Perfil dominante de compra</div><div class="cpBuyer" id="cpBuyerHeadline">—</div><div id="cpBuyerTags"></div></div><div class="card"><div class="label">Leitura rápida</div><div id="cpInsights" style="display:grid;gap:8px;margin-top:8px"></div></div></div>
      <div class="cpGrid" style="margin-top:11px"><div class="card"><div class="section" style="margin-top:0"><h2>Renda x compra</h2></div><div id="cpIncome"></div></div><div class="card"><div class="section" style="margin-top:0"><h2>Relacionamento</h2></div><div id="cpRelationship"></div></div></div>
      <div class="cpGrid" style="margin-top:11px"><div class="card"><div class="section" style="margin-top:0"><h2>Residência</h2></div><div id="cpHome"></div></div><div class="card"><div class="section" style="margin-top:0"><h2>Carros</h2></div><div id="cpCars"></div></div></div>
      <div class="cpGrid" style="margin-top:11px"><div class="card"><div class="section" style="margin-top:0"><h2>Profissões</h2></div><div id="cpProfessions"></div></div><div class="card"><div class="section" style="margin-top:0"><h2>Cidades / Estados</h2></div><div id="cpCities"></div></div></div>
    </div>`;const ref=document.getElementById('profile');ref?.parentNode.insertBefore(page,ref)}
    ['cpPeriod','cpScope','cpQual'].forEach(id=>{const el=document.getElementById(id);if(el&&!el.dataset.bound){el.dataset.bound='1';el.onchange=renderClientProfile}})
  }

  const arrAvg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
  const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
  const top=(rows,idx,limit=8)=>{const m={};rows.forEach(r=>{const v=String(r[idx]||'').trim();if(v&&v!=='NÃO INFORMADO'&&v!=='—')m[v]=(m[v]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,limit)};
  function list(rows,idx,limit=8){const all=top(rows,idx,limit),mx=all[0]?.[1]||1;return `<div class="cpList">${all.map(([k,v])=>`<div class="cpRow"><div><b>${k}</b><div class="cpBar"><i style="width:${v/mx*100}%"></i></div></div><b>${num(v)}</b><span class="tiny">${pct(v,rows.length)}</span></div>`).join('')||'<div class="empty">Sem dados.</div>'}</div>`}
  function incomeBand(v){if(!v)return 'Não informado';if(v<10000)return 'Até R$ 9,9 mil';if(v<15000)return 'R$ 10–14,9 mil';if(v<20000)return 'R$ 15–19,9 mil';if(v<30000)return 'R$ 20–29,9 mil';if(v<50000)return 'R$ 30–49,9 mil';return 'R$ 50 mil+'}
  function incomeTable(rows){const order=['Até R$ 9,9 mil','R$ 10–14,9 mil','R$ 15–19,9 mil','R$ 20–29,9 mil','R$ 30–49,9 mil','R$ 50 mil+','Não informado'],m={};rows.forEach(r=>{const b=incomeBand(r[1]);m[b]||(m[b]={n:0,b:0});m[b].n++;m[b].b+=r[13]?1:0});return `<table class="cpTable"><thead><tr><th>Faixa</th><th>Atendidos</th><th>Compradores</th><th>Conv.</th></tr></thead><tbody>${order.filter(k=>m[k]).map(k=>`<tr><td>${k}</td><td>${num(m[k].n)}</td><td>${num(m[k].b)}</td><td><b>${pct(m[k].b,m[k].n)}</b></td></tr>`).join('')}</tbody></table>`}
  function groupConv(rows,idx,limit=8){const m={};rows.forEach(r=>{const k=String(r[idx]||'NÃO INFORMADO');m[k]||(m[k]={n:0,b:0});m[k].n++;m[k].b+=r[13]?1:0});const a=Object.entries(m).sort((x,y)=>y[1].n-x[1].n).slice(0,limit);return `<table class="cpTable"><thead><tr><th>Perfil</th><th>Atendidos</th><th>Compram</th><th>Conv.</th></tr></thead><tbody>${a.map(([k,v])=>`<tr><td>${k}</td><td>${num(v.n)}</td><td>${num(v.b)}</td><td><b>${pct(v.b,v.n)}</b></td></tr>`).join('')}</tbody></table>`}
  function profTable(rows){const m={};rows.forEach(r=>[r[6],r[7]].forEach(p=>{p=String(p||'').trim();if(!p)return;m[p]||(m[p]={n:0,b:0});m[p].n++;if(r[13])m[p].b++}));const a=Object.entries(m).sort((x,y)=>y[1].n-x[1].n).slice(0,12);return `<table class="cpTable"><thead><tr><th>Profissão</th><th>Pessoas</th><th>Compradores</th><th>Índice*</th></tr></thead><tbody>${a.map(([k,v])=>`<tr><td>${k}</td><td>${num(v.n)}</td><td>${num(v.b)}</td><td><b>${pct(v.b,v.n)}</b></td></tr>`).join('')}</tbody></table><div class="tiny" style="margin-top:6px">*Índice por ocorrência da profissão nos casais atendidos.</div>`}
  function cityTable(rows){const cities=top(rows,8,7),ufs=top(rows,9,6);return `<div class="label">Cidades</div>${cities.map(([k,v])=>`<div class="member"><b>${k}</b><span class="tiny">${num(v)} atendimentos</span></div>`).join('')||'<div class="empty">Sem cidades.</div>'}<div class="label" style="margin-top:12px">Estados</div><div>${ufs.map(([k,v])=>`<span class="cpTag">${k} • ${num(v)}</span>`).join('')}</div>`}

  window.renderClientProfile=function(){mountUI();const all=readRows(),no=document.getElementById('cpNoData'),body=document.getElementById('cpBody'),st=document.getElementById('cpDataStatus');const mm=meta();if(st)st.textContent=mm?`${num(mm.rows)} atendimentos • até ${(mm.through||'').split('-').reverse().join('/')}`:'Sem dados de perfil carregados';if(!all.length){if(no)no.style.display='block';if(body)body.style.display='none';return}if(no)no.style.display='none';if(body)body.style.display='block';const period=document.getElementById('cpPeriod');if(period&&period.options.length===1){const months=[...new Set(all.map(r=>Number(String(r[0]).slice(5,7))).filter(Boolean))].sort((a,b)=>a-b);months.forEach(m=>period.insertAdjacentHTML('beforeend',`<option value="${m}">${MONTHS[m]} 2026</option>`))}
    let rows=[...all],pv=period?.value||'all',scope=document.getElementById('cpScope')?.value||'all',qf=document.getElementById('cpQual')?.value||'all';if(pv!=='all')rows=rows.filter(r=>Number(String(r[0]).slice(5,7))===Number(pv));if(scope==='buyers')rows=rows.filter(r=>r[13]);if(qf!=='all')rows=rows.filter(r=>r[12]===qf);const buyers=rows.filter(r=>r[13]),inc=rows.map(r=>Number(r[1])||0).filter(v=>v>0),bInc=buyers.map(r=>Number(r[1])||0).filter(v=>v>0),ages=rows.flatMap(r=>[r[10],r[11]]).map(Number).filter(v=>v>=18&&v<=90),carYears=rows.map(r=>Number(r[3])||0).filter(v=>v>=1980&&v<=2030),homeRows=rows.filter(r=>r[4]&&r[4]!=='NÃO INFORMADO'),own=homeRows.filter(r=>r[4]==='CASA PRÓPRIA').length;
    document.getElementById('cpRange').textContent=`${num(rows.length)} registros no filtro`;document.getElementById('cpStats').innerHTML=[['Atendimentos',num(rows.length),`${num(buyers.length)} compradores`],['Conversão de compra',pct(buyers.length,rows.length),'casal com contrato ATIVO'],['Renda média',money(arrAvg(inc)),`mediana ${money(median(inc))}`],['Renda de quem compra',money(arrAvg(bInc)),`${num(bInc.length)} compradores com renda`],['Casa própria',pct(own,homeRows.length),`${num(own)} de ${num(homeRows.length)} informados`],['Idade média',ages.length?`${arrAvg(ages).toFixed(1)} anos`:'—','pessoas informadas'],['Ano médio do carro',carYears.length?Math.round(arrAvg(carYears)):'—',`${num(carYears.length)} carros com ano`]].map(([l,v,s])=>`<div class="card stat"><span class="label">${l}</span><b>${v}</b><small>${s}</small></div>`).join('');
    const topRel=top(buyers,5,1)[0]?.[0]||'—',topCar=top(buyers,2,1)[0]?.[0]||'—',topProf=(()=>{const m={};buyers.forEach(r=>[r[6],r[7]].forEach(p=>{p=String(p||'').trim();if(p)m[p]=(m[p]||0)+1}));return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'})(),bHome=buyers.filter(r=>r[4]&&r[4]!=='NÃO INFORMADO'),bOwn=bHome.filter(r=>r[4]==='CASA PRÓPRIA').length,bandCounts={};buyers.forEach(r=>{const b=incomeBand(r[1]);if(b!=='Não informado')bandCounts[b]=(bandCounts[b]||0)+1});const topBand=Object.entries(bandCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';document.getElementById('cpBuyerHeadline').textContent=buyers.length?`${topBand} • ${topRel}`:'Sem compradores no filtro';document.getElementById('cpBuyerTags').innerHTML=buyers.length?`<span class="cpTag">Renda média ${money(arrAvg(bInc))}</span><span class="cpTag">Casa própria ${pct(bOwn,bHome.length)}</span><span class="cpTag">Carro: ${topCar}</span><span class="cpTag">Profissão: ${topProf}</span>`:'';
    const allInc=arrAvg(inc),buyerInc=arrAvg(bInc),delta=allInc?((buyerInc/allInc-1)*100):0;document.getElementById('cpInsights').innerHTML=`<div class="insight"><b>Quem compra ganha quanto?</b>Renda média dos compradores: <span class="green">${money(buyerInc)}</span>${allInc?` • ${delta>=0?'+':''}${delta.toFixed(1)}% vs. média geral`:''}.</div><div class="insight"><b>Moradia</b>${buyers.length?`${pct(bOwn,bHome.length)} dos compradores com informação têm casa própria.`:'Sem compradores no filtro.'}</div><div class="insight"><b>Relacionamento dominante</b>${topRel} entre os compradores.</div><div class="insight"><b>Sinal comercial</b>${buyers.length?`Cruze renda, profissão, carro e moradia nas tabelas abaixo para ver onde a conversão é maior.`:'Altere os filtros ou carregue uma base com vendas.'}</div>`;
    document.getElementById('cpIncome').innerHTML=incomeTable(rows);document.getElementById('cpRelationship').innerHTML=groupConv(rows,5,8);document.getElementById('cpHome').innerHTML=groupConv(rows,4,6);document.getElementById('cpCars').innerHTML=groupConv(rows,2,10);document.getElementById('cpProfessions').innerHTML=profTable(rows);document.getElementById('cpCities').innerHTML=cityTable(rows);
  };

  mountUI();const oldShow=window.show;if(typeof oldShow==='function'&&!oldShow.__cpWrapped){const wrapped=function(p){oldShow(p);if(p==='clientprofile')renderClientProfile()};wrapped.__cpWrapped=true;window.show=wrapped}window.addEventListener('tx-client-data-updated',renderClientProfile);setTimeout(()=>{mountUI();mountUploadHook();renderClientProfile()},500);
})();
