// TARGET X — Perfil de Casais / inteligência comercial
(function(){
  if(window.__txClientProfileLoaded)return;window.__txClientProfileLoaded=true;
  const STORE='tx_client_profile_v2',META='tx_client_profile_meta_v2';
  const MONTHS=['','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
  const css=document.createElement('style');css.textContent=`
  .cpFilters{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:8px}.cpGrid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.cpHero{display:grid;grid-template-columns:1.2fr .8fr;gap:11px}.cpHeadline{font-size:clamp(25px,4vw,42px);font-weight:1000;line-height:1.05;color:var(--green);margin:8px 0}.cpHeadline.red{color:var(--red)}.cpTag{display:inline-block;padding:6px 8px;border:1px solid var(--line);border-radius:99px;margin:3px 4px 0 0;font-size:10px}.cpTable{width:100%;border-collapse:collapse}.cpTable th,.cpTable td{padding:8px;border-bottom:1px solid #14271f;text-align:left}.cpTable th{font-size:9px;color:var(--muted);text-transform:uppercase}.cpTable td:nth-child(n+2),.cpTable th:nth-child(n+2){text-align:right}.cpHint{padding:16px;border:1px dashed #315c47;border-radius:14px;background:#06100b}.cpHint b{display:block;margin-bottom:5px}.cpRisk{border-color:#5d2630!important}.cpRisk .label{color:#ff9da7}.cpGood .label{color:#b8ff2c}.cpMini{font-size:10px;color:var(--muted);margin-top:5px}
  @media(max-width:900px){.cpGrid,.cpHero{grid-template-columns:1fr}.cpFilters{grid-template-columns:1fr 1fr}}@media(max-width:560px){.cpFilters{grid-template-columns:1fr}.cpTable{font-size:11px}}
  `;document.head.appendChild(css);

  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
  const n=v=>{if(typeof v==='number')return isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/R\$|\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0};
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
  const num=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(Math.round(v||0));
  const pct=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'0%';
  const get=(row,...names)=>{const ks=Object.keys(row);for(const name of names){const target=norm(name),k=ks.find(k=>norm(k)===target);if(k!==undefined)return row[k]}return ''};
  function ymd(v){if(!v)return '';if(typeof v==='number'&&window.XLSX?.SSF?.parse_date_code){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`;}let s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);if(!isNaN(d))return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return ''}
  function cleanRel(v){const x=norm(v);if(!x)return 'NÃO INFORMADO';if(x==='UNIAO ESTAVEL')return 'UNIÃO ESTÁVEL';if(x==='CASADO'||x==='CASADA')return 'CASADO';if(x==='NOIVOS'||x==='NOIVO'||x==='NOIVA')return 'NOIVOS';if(x==='NAMORADOS'||x==='NAMORADO'||x==='NAMORADA')return 'NAMORADOS';if(x==='SOLTEIRO'||x==='SOLTEIRA')return 'SOLTEIRO';return String(v).trim().toUpperCase()}
  function cleanHome(v){const x=norm(v);if(!x||x==='NAO SELECIONADO')return 'NÃO INFORMADO';if(x.includes('VERIFICADO')||x.includes('PROPRIA')||x==='SIM')return 'CASA PRÓPRIA';if(x==='NAO'||x.includes('ALUG'))return 'SEM CASA PRÓPRIA';return String(v).trim().toUpperCase()}
  function qual(v){const x=norm(v);if(/^Q\b/.test(x)||x.includes('PERFIL QUALIFICADO'))return 'Q';if(/^NQ\b/.test(x))return 'NQ';return '—'}
  function compact(row){
    const date=ymd(get(row,'Data de atendimento','Data'));if(!date)return null;
    const status=norm(get(row,'Status do contrato','Status contrato'));
    const buyer=/\bATIVO\b/.test(status)?1:0,cancelled=/CANCEL/.test(status)?1:0;
    return [date,n(get(row,'Renda','Renda Bruta','Renda familiar')),String(get(row,'Carro 1','Carro','Veículo','Veiculo')||'').trim().toUpperCase(),Math.round(n(get(row,'Ano carro 1','Ano carro','Ano do carro')))||0,cleanHome(get(row,'Residência própria','Residencia propria','Casa própria','Casa propria')),cleanRel(get(row,'Tipo de relacionamento','Relacionamento','Estado civil')),String(get(row,'Profissão 1','Profissao 1','Profissão','Profissao')||'').trim(),String(get(row,'Profissão 2','Profissao 2')||'').trim(),String(get(row,'Cidade')||'').trim(),String(get(row,'UF','Estado')||'').trim().toUpperCase(),Math.round(n(get(row,'Idade 1','Idade')))||0,Math.round(n(get(row,'Idade 2')))||0,qual(get(row,'Qualificação','Qualificacao','Motivo de qualificação','Motivo de qualificacao')),buyer,n(get(row,'Valor vendido','VGV','VGV Geral')),cancelled];
  }
  const readRows=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return []}};
  function saveRows(rows,file){try{localStorage.setItem(STORE,JSON.stringify(rows));const dates=rows.map(r=>r[0]).filter(Boolean).sort();localStorage.setItem(META,JSON.stringify({file:file||'',rows:rows.length,from:dates[0]||'',through:dates.at(-1)||'',when:new Date().toISOString()}));return true}catch(e){console.warn(e);return false}}
  const meta=()=>{try{return JSON.parse(localStorage.getItem(META)||'null')}catch{return null}};
  async function ensureXlsx(){if(window.XLSX)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  async function importClientFile(file){if(!file)return;const status=document.getElementById('cpDataStatus');if(status)status.textContent='Lendo perfil dos casais...';try{await ensureXlsx();const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:false});let rows=[];wb.SheetNames.forEach(sn=>{XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:'',raw:true}).forEach(r=>{const c=compact(r);if(c)rows.push(c)})});if(!rows.length)throw new Error('Não encontrei registros de casais na planilha.');if(!saveRows(rows,file.name))throw new Error('O navegador não conseguiu salvar os dados do perfil.');window.dispatchEvent(new CustomEvent('tx-client-data-updated',{detail:{rows:rows.length,file:file.name}}));renderClientProfile();const up=document.getElementById('txUploadStatus');if(up)up.innerHTML=`<span class="green">✓ Perfil Casais atualizado.</span> ${num(rows.length)} atendimentos lidos.`}catch(e){console.warn(e);if(status)status.innerHTML=`<span class="red">${e.message||e}</span>`}}
  }
  function mountUploadHook(){const fi=document.getElementById('txSheetFile');if(!fi||fi.dataset.cpHook)return false;fi.dataset.cpHook='1';fi.addEventListener('change',()=>{const f=fi.files?.[0];if(f)importClientFile(f)});return true}
  let hookTries=0;const hookTimer=setInterval(()=>{if(mountUploadHook()||++hookTries>30)clearInterval(hookTimer)},300);

  function mountUI(){
    const nav=document.querySelector('.tabs');if(!nav)return;
    const professional=[...nav.querySelectorAll('.tab')].find(b=>b.dataset.page==='profile');if(professional)professional.textContent='Profissional';
    const couples=[...nav.querySelectorAll('.tab')].find(b=>b.dataset.page==='clientprofile');if(couples){couples.textContent='Perfil Casais';couples.onclick=()=>{if(typeof show==='function')show('clientprofile');renderClientProfile()}}
    if(!couples){const b=document.createElement('button');b.className='tab';b.dataset.page='clientprofile';b.textContent='Perfil Casais';nav.insertBefore(b,professional||nav.children[3]||null);b.onclick=()=>{if(typeof show==='function')show('clientprofile');renderClientProfile()}}
    if(!document.getElementById('clientprofile')){const page=document.createElement('section');page.className='page';page.id='clientprofile';page.innerHTML=`
      <div class="section"><div><h2>Perfil de Casais</h2><div class="meta">Renda, comportamento de compra e risco de cancelamento.</div></div><div class="meta" id="cpDataStatus"></div></div>
      <div class="card"><div class="cpFilters"><select id="cpPeriod"><option value="all">Ano 2026</option></select><select id="cpScope"><option value="all">Todos os casais</option><option value="buyers">Somente compradores</option><option value="cancelled">Somente cancelados</option></select><select id="cpQual"><option value="all">Q + NQ</option><option value="Q">Somente Q</option><option value="NQ">Somente NQ</option></select></div></div>
      <div id="cpNoData" class="cpHint" style="margin-top:11px;display:none"><b>Carregue a planilha oficial uma vez.</b>O TARGET X vai montar o perfil dos casais usando renda, profissão, carro, casa própria, relacionamento, idade, cidade, compra e cancelamento.</div>
      <div id="cpBody">
        <div class="section"><h2>Visão geral</h2><span class="meta" id="cpRange"></span></div><div class="stats" id="cpStats"></div>
        <div class="section"><h2>Quem mais compra</h2><span class="meta">perfil dominante entre compradores</span></div><div class="cpHero"><div class="card cpGood"><div class="label">Perfil de compra</div><div class="cpHeadline" id="cpBuyerHeadline">—</div><div id="cpBuyerTags"></div></div><div class="card"><div class="label">Leitura comercial</div><div id="cpBuyerInsights" style="display:grid;gap:8px;margin-top:8px"></div></div></div>
        <div class="section"><h2>Quem mais cancela</h2><span class="meta">perfil dominante + taxa de risco</span></div><div class="cpHero"><div class="card cpRisk"><div class="label">Perfil de cancelamento</div><div class="cpHeadline red" id="cpCancelHeadline">—</div><div id="cpCancelTags"></div></div><div class="card"><div class="label">Leitura de risco</div><div id="cpCancelInsights" style="display:grid;gap:8px;margin-top:8px"></div></div></div>
        <div class="cpGrid" style="margin-top:11px"><div class="card"><div class="section" style="margin-top:0"><h2>Renda x resultado</h2></div><div id="cpIncome"></div></div><div class="card"><div class="section" style="margin-top:0"><h2>Relacionamento</h2></div><div id="cpRelationship"></div></div></div>
        <div class="cpGrid" style="margin-top:11px"><div class="card"><div class="section" style="margin-top:0"><h2>Residência</h2></div><div id="cpHome"></div></div><div class="card"><div class="section" style="margin-top:0"><h2>Carros</h2></div><div id="cpCars"></div></div></div>
        <div class="cpGrid" style="margin-top:11px"><div class="card"><div class="section" style="margin-top:0"><h2>Profissões</h2></div><div id="cpProfessions"></div></div><div class="card"><div class="section" style="margin-top:0"><h2>Cidades / Estados</h2></div><div id="cpCities"></div></div></div>
      </div>`;const ref=document.getElementById('profile');ref?.parentNode.insertBefore(page,ref)}
    ['cpPeriod','cpScope','cpQual'].forEach(id=>{const el=document.getElementById(id);if(el&&!el.dataset.bound){el.dataset.bound='1';el.onchange=renderClientProfile}})
  }

  const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
  const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
  const top=(rows,idx,limit=8)=>{const m={};rows.forEach(r=>{const v=String(r[idx]||'').trim();if(v&&v!=='NÃO INFORMADO'&&v!=='—')m[v]=(m[v]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,limit)};
  function incomeBand(v){if(!v)return 'Não informado';if(v<10000)return 'Até R$ 9,9 mil';if(v<15000)return 'R$ 10–14,9 mil';if(v<20000)return 'R$ 15–19,9 mil';if(v<30000)return 'R$ 20–29,9 mil';if(v<50000)return 'R$ 30–49,9 mil';return 'R$ 50 mil+'}
  const resultCell=v=>`<td><b>${v}</b></td>`;
  function grouped(rows,keyFn,limit=10){const m={};rows.forEach(r=>{const k=keyFn(r)||'NÃO INFORMADO';m[k]||(m[k]={n:0,b:0,c:0,s:0});m[k].n++;m[k].b+=r[13]?1:0;m[k].c+=r[15]?1:0;m[k].s+=(r[13]||r[15])?1:0});return Object.entries(m).sort((a,b)=>b[1].n-a[1].n).slice(0,limit)}
  function outcomeTable(groups,label='Perfil'){return `<table class="cpTable"><thead><tr><th>${label}</th><th>Atendidos</th><th>Compram</th><th>Cancelam</th><th>Conv.</th><th>Cancel.*</th></tr></thead><tbody>${groups.map(([k,v])=>`<tr><td>${k}</td><td>${num(v.n)}</td><td>${num(v.b)}</td><td>${num(v.c)}</td>${resultCell(pct(v.b,v.n))}${resultCell(pct(v.c,v.s))}</tr>`).join('')}</tbody></table><div class="cpMini">*Cancelamento = casais cancelados ÷ casais com contrato ativo ou cancelado.</div>`}
  function incomeTable(rows){const order=['Até R$ 9,9 mil','R$ 10–14,9 mil','R$ 15–19,9 mil','R$ 20–29,9 mil','R$ 30–49,9 mil','R$ 50 mil+','Não informado'];const m=Object.fromEntries(grouped(rows,r=>incomeBand(r[1]),99));return outcomeTable(order.filter(k=>m[k]).map(k=>[k,m[k]]),'Faixa de renda')}
  function profTable(rows){const m={};rows.forEach(r=>[r[6],r[7]].forEach(p=>{p=String(p||'').trim();if(!p)return;m[p]||(m[p]={n:0,b:0,c:0,s:0});m[p].n++;if(r[13])m[p].b++;if(r[15])m[p].c++;if(r[13]||r[15])m[p].s++}));return outcomeTable(Object.entries(m).sort((a,b)=>b[1].n-a[1].n).slice(0,12),'Profissão')}
  function cityTable(rows){const cities=top(rows,8,8),ufs=top(rows,9,8);return `<div class="label">Cidades</div>${cities.map(([k,v])=>`<div class="member"><b>${k}</b><span class="tiny">${num(v)} atendimentos</span></div>`).join('')||'<div class="empty">Sem cidades.</div>'}<div class="label" style="margin-top:12px">Estados</div><div>${ufs.map(([k,v])=>`<span class="cpTag">${k} • ${num(v)}</span>`).join('')}</div>`}
  function topProfession(rows){const m={};rows.forEach(r=>[r[6],r[7]].forEach(p=>{p=String(p||'').trim();if(p)m[p]=(m[p]||0)+1}));return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'}
  function dominant(rows,idx){return top(rows,idx,1)[0]?.[0]||'—'}
  function topBand(rows){const m={};rows.forEach(r=>{const k=incomeBand(r[1]);if(k!=='Não informado')m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'}
  function riskGroup(rows,keyFn,minContracts=3){const groups=grouped(rows,keyFn,99).filter(([,v])=>v.s>=minContracts);return groups.sort((a,b)=>(b[1].c/b[1].s)-(a[1].c/a[1].s)||b[1].c-a[1].c)[0]||null}

  window.renderClientProfile=function(){
    mountUI();const all=readRows(),no=document.getElementById('cpNoData'),body=document.getElementById('cpBody'),st=document.getElementById('cpDataStatus'),mm=meta();if(st)st.textContent=mm?`${num(mm.rows)} casais • até ${(mm.through||'').split('-').reverse().join('/')}`:'Sem dados de perfil carregados';if(!all.length){if(no)no.style.display='block';if(body)body.style.display='none';return}if(no)no.style.display='none';if(body)body.style.display='block';
    const period=document.getElementById('cpPeriod');if(period&&period.options.length===1){[...new Set(all.map(r=>Number(String(r[0]).slice(5,7))).filter(Boolean))].sort((a,b)=>a-b).forEach(m=>period.insertAdjacentHTML('beforeend',`<option value="${m}">${MONTHS[m]} 2026</option>`))}
    let rows=[...all],pv=period?.value||'all',scope=document.getElementById('cpScope')?.value||'all',qf=document.getElementById('cpQual')?.value||'all';if(pv!=='all')rows=rows.filter(r=>Number(String(r[0]).slice(5,7))===Number(pv));if(scope==='buyers')rows=rows.filter(r=>r[13]);if(scope==='cancelled')rows=rows.filter(r=>r[15]);if(qf!=='all')rows=rows.filter(r=>r[12]===qf);
    const buyers=rows.filter(r=>r[13]),cancelled=rows.filter(r=>r[15]),contracted=rows.filter(r=>r[13]||r[15]);
    const inc=rows.map(r=>+r[1]||0).filter(v=>v>0),bInc=buyers.map(r=>+r[1]||0).filter(v=>v>0),cInc=cancelled.map(r=>+r[1]||0).filter(v=>v>0),ages=rows.flatMap(r=>[r[10],r[11]]).map(Number).filter(v=>v>=18&&v<=90),carYears=rows.map(r=>+r[3]||0).filter(v=>v>=1980&&v<=2030),homeRows=rows.filter(r=>r[4]&&r[4]!=='NÃO INFORMADO'),own=homeRows.filter(r=>r[4]==='CASA PRÓPRIA').length;
    document.getElementById('cpRange').textContent=`${num(rows.length)} casais no filtro`;
    document.getElementById('cpStats').innerHTML=[['Casais atendidos',num(rows.length),`${num(buyers.length)} compradores`],['Conversão de compra',pct(buyers.length,rows.length),'casais com contrato ATIVO'],['Cancelamentos',num(cancelled.length),`${pct(cancelled.length,contracted.length)} dos casais com contrato`],['Renda média',money(avg(inc)),`mediana ${money(median(inc))}`],['Renda de quem compra',money(avg(bInc)),`${num(bInc.length)} compradores com renda`],['Renda de quem cancela',money(avg(cInc)),`${num(cInc.length)} cancelados com renda`],['Casa própria',pct(own,homeRows.length),`${num(own)} de ${num(homeRows.length)} informados`],['Idade média',ages.length?`${avg(ages).toFixed(1)} anos`:'—','pessoas informadas'],['Ano médio do carro',carYears.length?Math.round(avg(carYears)):'—',`${num(carYears.length)} carros com ano`]].map(([l,v,s])=>`<div class="card stat"><span class="label">${l}</span><b>${v}</b><small>${s}</small></div>`).join('');

    const bHome=buyers.filter(r=>r[4]&&r[4]!=='NÃO INFORMADO'),bOwn=bHome.filter(r=>r[4]==='CASA PRÓPRIA').length,bRel=dominant(buyers,5),bCar=dominant(buyers,2),bProf=topProfession(buyers),bBand=topBand(buyers);
    document.getElementById('cpBuyerHeadline').textContent=buyers.length?`${bBand} • ${bRel}`:'Sem compradores no filtro';document.getElementById('cpBuyerTags').innerHTML=buyers.length?`<span class="cpTag">Renda média ${money(avg(bInc))}</span><span class="cpTag">Casa própria ${pct(bOwn,bHome.length)}</span><span class="cpTag">Carro: ${bCar}</span><span class="cpTag">Profissão: ${bProf}</span>`:'';
    const delta=avg(inc)?((avg(bInc)/avg(inc)-1)*100):0;document.getElementById('cpBuyerInsights').innerHTML=`<div class="insight"><b>Renda de quem compra</b><span class="green">${money(avg(bInc))}</span>${inc.length&&bInc.length?` • ${delta>=0?'+':''}${delta.toFixed(1)}% vs. renda média geral`:''}.</div><div class="insight"><b>Relacionamento dominante</b>${bRel}.</div><div class="insight"><b>Carro mais comum</b>${bCar}.</div><div class="insight"><b>Profissão mais frequente</b>${bProf}.</div>`;

    const cHome=cancelled.filter(r=>r[4]&&r[4]!=='NÃO INFORMADO'),cOwn=cHome.filter(r=>r[4]==='CASA PRÓPRIA').length,cRel=dominant(cancelled,5),cCar=dominant(cancelled,2),cProf=topProfession(cancelled),cBand=topBand(cancelled),riskIncome=riskGroup(rows,r=>incomeBand(r[1])),riskRel=riskGroup(rows,r=>r[5]),riskHome=riskGroup(rows,r=>r[4]);
    document.getElementById('cpCancelHeadline').textContent=cancelled.length?`${cBand} • ${cRel}`:'Sem cancelamentos no filtro';document.getElementById('cpCancelTags').innerHTML=cancelled.length?`<span class="cpTag">Renda média ${money(avg(cInc))}</span><span class="cpTag">Casa própria ${pct(cOwn,cHome.length)}</span><span class="cpTag">Carro: ${cCar}</span><span class="cpTag">Profissão: ${cProf}</span>`:'';
    const riskText=(g)=>g?`${g[0]} • ${pct(g[1].c,g[1].s)} (${num(g[1].c)}/${num(g[1].s)})`:'Amostra insuficiente';document.getElementById('cpCancelInsights').innerHTML=`<div class="insight"><b>Renda de quem cancela</b><span class="red">${money(avg(cInc))}</span>.</div><div class="insight"><b>Faixa de renda com maior taxa*</b>${riskText(riskIncome)}</div><div class="insight"><b>Relacionamento com maior taxa*</b>${riskText(riskRel)}</div><div class="insight"><b>Moradia com maior taxa*</b>${riskText(riskHome)}</div><div class="cpMini">*Considera grupos com pelo menos 3 casais que tiveram contrato ativo ou cancelado.</div>`;

    document.getElementById('cpIncome').innerHTML=incomeTable(rows);document.getElementById('cpRelationship').innerHTML=outcomeTable(grouped(rows,r=>r[5],8),'Relacionamento');document.getElementById('cpHome').innerHTML=outcomeTable(grouped(rows,r=>r[4],6),'Residência');document.getElementById('cpCars').innerHTML=outcomeTable(grouped(rows,r=>r[2],10),'Carro');document.getElementById('cpProfessions').innerHTML=profTable(rows);document.getElementById('cpCities').innerHTML=cityTable(rows);
  };

  mountUI();const oldShow=window.show;if(typeof oldShow==='function'&&!oldShow.__cpWrapped){const wrapped=function(p){oldShow(p);if(p==='clientprofile')renderClientProfile()};wrapped.__cpWrapped=true;window.show=wrapped}window.addEventListener('tx-client-data-updated',renderClientProfile);setTimeout(()=>{mountUI();mountUploadHook();renderClientProfile()},500);
})();
