// TARGET X — print do ranking + fechamento oficial 06/09 e 07/09
(function(){
  // A planilha enviada em 08/09 passa a ser a fonte oficial para 06 e 07/09.
  if(!document.querySelector('script[data-tx-official-0607]')){
    const s=document.createElement('script');s.async=false;s.src='official-0607-corrected.js?v=48';s.dataset.txOfficial0607='1';document.head.appendChild(s);
  }

  const css=document.createElement('style');
  css.textContent=`#rankPrintBtn{margin-left:auto;background:var(--green);color:#051006;border-color:var(--green)}#rankPrintOverlay{display:none;position:fixed;inset:0;z-index:10000;background:#020604;overflow:auto;padding:8px}#rankPrintOverlay.open{display:block}.rankPrintSheet{max-width:820px;margin:0 auto;background:linear-gradient(180deg,#0b1b13,#07100c);border:1px solid #183b2b;border-radius:16px;padding:12px}.rankPrintHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;border-bottom:1px solid #183b2b;padding-bottom:9px}.rankPrintBrand{font-size:9px;letter-spacing:1.4px;color:#85aa98}.rankPrintTitle{font-size:22px;font-weight:1000;margin:2px 0}.rankPrintPeriod{color:#b8ff2c;font-size:12px;font-weight:900}.rankPrintMain{text-align:right}.rankPrintMain small{display:block;color:#85aa98;font-size:8px}.rankPrintMain b{display:block;color:#b8ff2c;font-size:24px}.rankPrintStats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:8px 0}.rankPrintStat{border:1px solid #183b2b;border-radius:9px;padding:6px 7px;background:#07120d}.rankPrintStat small{display:block;color:#85aa98;font-size:7px}.rankPrintStat b{display:block;font-size:12px;margin-top:2px}.rankPrintTable{width:100%;border-collapse:collapse;font-size:9px}.rankPrintTable th{color:#85aa98;font-size:7px;border-bottom:1px solid #183b2b;padding:4px 3px;text-align:left}.rankPrintTable td{border-bottom:1px solid #13261e;padding:4px 3px}.rankPrintTable td:nth-child(n+3){text-align:right;white-space:nowrap}.rankPrintVgv{color:#b8ff2c;font-weight:1000}.rankPrintActions{max-width:820px;margin:8px auto;display:flex;gap:8px}.rankPrintActions button{flex:1}@media(max-width:520px){#rankPrintOverlay{padding:3px}.rankPrintSheet{padding:7px}.rankPrintTitle{font-size:17px}.rankPrintMain b{font-size:19px}.rankPrintStats{gap:3px;margin:5px 0}.rankPrintStat{padding:4px}.rankPrintStat b{font-size:9px}.rankPrintTable{font-size:7.2px}.rankPrintTable th,.rankPrintTable td{padding:2.5px 2px}.rankPrintTable td:nth-child(2){max-width:155px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}`;
  document.head.appendChild(css);

  function ensureButton(){const sec=document.querySelector('#rank .section');if(!sec||document.getElementById('rankPrintBtn'))return;const b=document.createElement('button');b.id='rankPrintBtn';b.textContent='📸 Modo Print';b.onclick=openPrint;sec.appendChild(b)}
  function summary(label){const c=[...document.querySelectorAll('#rankSummary .stat')].find(x=>x.querySelector('.label')?.innerText.trim().toUpperCase()===label.toUpperCase());return c?.querySelector('b')?.innerText.trim()||'—'}
  function rows(){return [...document.querySelectorAll('#rankBody tr')].map(tr=>{const td=tr.querySelectorAll('td');if(td.length<10)return null;return{pos:td[0].innerText.trim(),name:td[1].innerText.trim().split('\n')[0],couples:td[3].innerText.trim(),sales:td[6].innerText.trim(),vgvGeneral:td[8].innerText.trim(),vgvAtivo:td[9].innerText.trim()}}).filter(Boolean)}
  function period(){const s=document.getElementById('rankPeriod');return s?.options[s.selectedIndex]?.text||'Ranking 2026'}
  function openPrint(){const rr=rows();if(!rr.length)return alert('Não há dados para este ranking.');let o=document.getElementById('rankPrintOverlay');if(!o){o=document.createElement('div');o.id='rankPrintOverlay';document.body.appendChild(o)}o.innerHTML=`<div class="rankPrintSheet"><div class="rankPrintHead"><div><div class="rankPrintBrand">TARGET X • PERFORMANCE COMMAND</div><div class="rankPrintTitle">RANKING DE PERFORMANCE</div><div class="rankPrintPeriod">${period()}</div></div><div class="rankPrintMain"><small>VGV GERAL</small><b>${summary('VGV Geral')}</b></div></div><div class="rankPrintStats"><div class="rankPrintStat"><small>Profissionais</small><b>${summary('Profissionais')}</b></div><div class="rankPrintStat"><small>Casais</small><b>${summary('Casais')}</b></div><div class="rankPrintStat"><small>Vendas</small><b>${summary('Vendas')}</b></div><div class="rankPrintStat"><small>VGV Ativo</small><b>${summary('VGV Ativo')}</b></div><div class="rankPrintStat"><small>NoTour</small><b>${summary('NoTour')}</b></div><div class="rankPrintStat"><small>Brindes</small><b>${summary('Brindes')}</b></div></div><table class="rankPrintTable"><thead><tr><th>#</th><th>Profissional</th><th>Casais</th><th>Vendas</th><th>VGV Geral</th><th>VGV Ativo</th></tr></thead><tbody>${rr.map(r=>`<tr><td>${r.pos}</td><td>${r.name}</td><td>${r.couples}</td><td>${r.sales}</td><td class="rankPrintVgv">${r.vgvGeneral}</td><td>${r.vgvAtivo}</td></tr>`).join('')}</tbody></table></div><div class="rankPrintActions"><button id="rankPrintBack">← Voltar</button><button class="primary" id="rankPrintFull">Tela cheia</button></div>`;o.classList.add('open');document.getElementById('rankPrintBack').onclick=()=>o.classList.remove('open');document.getElementById('rankPrintFull').onclick=()=>document.documentElement.requestFullscreen?.();window.scrollTo(0,0)}
  const old=window.renderRank;if(typeof old==='function')window.renderRank=function(){old();setTimeout(ensureButton,0)};document.addEventListener('click',e=>{if(e.target?.dataset?.page==='rank')setTimeout(ensureButton,0)});setTimeout(ensureButton,500);
})();

// Módulos auxiliares.
(function(){if(document.querySelector('script[data-tx-upload]'))return;const s=document.createElement('script');s.async=false;s.src='upload-import.js?v=48';s.dataset.txUpload='1';document.head.appendChild(s)})();
(function(){if(document.querySelector('script[data-tx-client-profile]'))return;const s=document.createElement('script');s.async=false;s.src='client-profile.js?v=54';s.dataset.txClientProfile='1';document.head.appendChild(s)})();
(function(){if(document.querySelector('script[data-tx-profile-explorer]'))return;const s=document.createElement('script');s.async=false;s.src='profile-explorer.js?v=57';s.dataset.txProfileExplorer='1';document.head.appendChild(s)})();
(function(){if(document.querySelector('script[data-tx-cloud]'))return;const s=document.createElement('script');s.async=false;s.src='cloud-sync.js?v=48';s.dataset.txCloud='1';document.head.appendChild(s)})();
(function(){if(document.querySelector('script[data-tx-alerts]'))return;const s=document.createElement('script');s.async=false;s.src='alerts.js?v=48';s.dataset.txAlerts='1';document.head.appendChild(s)})();