// TARGET X v6.1 — Planilha oficial como fonte única + Perfil Casais completo
(function(){
  if(window.__txOfficialImporterV61)return;window.__txOfficialImporterV61=true;
  const ROWS='tx_official_daily_v60',META='tx_official_meta_v60',BACKUP='tx_official_backup_v60';
  const PSTORE='tx_couples_profile_v54',PMETA='tx_couples_profile_meta_v54';
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
  const n=v=>{if(typeof v==='number')return isFinite(v)?v:0;let s=String(v??'').trim().replace(/R\$|\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0};
  const num=v=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(v)||0));
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(v)||0);
  const css=document.createElement('style');css.textContent=`#txUploadBar{margin:10px 0 2px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;border-color:#28533d}#txUploadBar .txUpTitle{font-weight:1000;font-size:13px}.txUpStatus{font-size:10px;color:var(--muted);margin-top:4px}#txUploadActions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}#txSheetFile{display:none}#txChooseSheet{background:#102b1f;border-color:#2a6248;color:#c9ffe1}#txConfirmSheet{background:var(--green);color:#061006;border-color:var(--green)}.txFileName{max-width:240px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:10px;color:var(--muted)}#txImportPreview{display:none;margin:8px 0 12px;border:1px solid var(--line);border-radius:16px;padding:12px;background:#06100b}.txPreviewGrid{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.txPV{border:1px solid var(--line);border-radius:10px;padding:8px}.txPV span{display:block;font-size:8px;color:var(--muted);text-transform:uppercase}.txPV b{display:block;margin-top:4px}@media(max-width:1050px){.txPreviewGrid{grid-template-columns:repeat(4,1fr)}}@media(max-width:900px){.txPreviewGrid{grid-template-columns:repeat(3,1fr)}}@media(max-width:720px){#txUploadBar{grid-template-columns:1fr}#txUploadActions{justify-content:stretch}#txUploadActions button{flex:1}.txFileName{max-width:100%}}@media(max-width:520px){.txPreviewGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(css);
  const aliases={'JOSYENE FREITAS':'JOSYENE APARECIDA DE FREITAS','ANA CAROLINE':'ANA CAROLINE DA SILVA LOPES PEREIRA','ADRIANO MOREIRA':'EDSON ADRIANO PINTO MOREIRA','MARCIO ALFAIA':'MARCIO VINICIOS MARTINS ALFAIA','ANDRE CARRICO':'ANDRE LUIS CARRIÇO DOS SANTOS','JESSICA BARBOSA':'JESSICA GONCALVES BARBOSA','MATHEUS DOMINGOS SANTOS':'MATHEUS DOMINGOS SANTOS DE SOUZA','LETICIA LEANDRA':'LETICIA LEANDRA DE TOLEDO','OTAVIO JOSE DE OLIVEIRA MARTIN':'OTAVIO JOSE DE OLIVEIRA MARTINS'};
  let candidate=null;
  function get(row,...names){const ks=Object.keys(row);for(const name of names){const t=norm(name),k=ks.find(k=>norm(k)===t);if(k!==undefined)return row[k]}return''}
  function ymd(v){if(!v)return'';if(typeof v==='number'&&window.XLSX?.SSF?.parse_date_code){const d=XLSX.SSF.parse_date_code(v);if(d)return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function resolvePerson(raw){const r=norm(raw);if(!r)return'';const ak=Object.keys(aliases).find(k=>norm(k)===r);if(ak)return aliases[ak];const exact=(window.HIST||[]).find(p=>norm(p.name)===r);if(exact)return exact.name;const toks=r.split(' ').filter(x=>x.length>2);let best=null,score=0;(window.HIST||[]).forEach(p=>{const pt=new Set(norm(p.name).split(' ')),hit=toks.filter(t=>pt.has(t)).length,s=hit/Math.max(1,toks.length);if(hit&&s>score){score=s;best=p.name}});return score>=.5?best:String(raw).trim().toUpperCase()}
  function countStatus(status,rx){return String(status||'').split('#').map(norm).filter(x=>rx.test(x)).length}
  function contractCounts(status){const parts=String(status||'').split('#').map(x=>norm(x)).filter(Boolean);let active=0,cancel=0;parts.forEach(p=>{if(/^ATIVO\b/.test(p))active++;else if(/^CANCEL/.test(p))cancel++});return{active,cancel,total:active+cancel}}
  function profileRel(v){const x=norm(v);if(!x)return'NÃO INFORMADO';if(x==='UNIAO ESTAVEL')return'UNIÃO ESTÁVEL';if(/CASAD/.test(x))return'CASADO';if(/NOIV/.test(x))return'NOIVOS';if(/NAMORAD/.test(x))return'NAMORADOS';if(/SOLTEIR/.test(x))return'SOLTEIRO';return String(v).trim().toUpperCase()}
  function profileHome(v){const x=norm(v);if(!x||x==='NAO SELECIONADO')return'NÃO INFORMADO';if(x.includes('PROPRIA')||x.includes('VERIFICADO')||x==='SIM')return'CASA PRÓPRIA';if(x==='NAO'||x.includes('ALUG'))return'SEM CASA PRÓPRIA';return String(v).trim().toUpperCase()}
  function profileQual(v){const x=norm(v);if(/^Q\b/.test(x)||x.includes('PERFIL QUALIFICADO'))return'Q';if(/^NQ\b/.test(x))return'NQ';return'—'}
  function validAge(v){v=Math.round(n(v));return v>=18&&v<=90?v:0}
  function parseProfileRow(row){const date=ymd(get(row,'Data','Data de atendimento'));if(!date)return null;const cc=contractCounts(get(row,'Status do contrato','Status contrato')),gross=n(get(row,'Valor vendido','VGV','VGV Geral','VGV bruto')),explicitActive=n(get(row,'VGV ativo','VGV Ativo')),activeVgv=explicitActive||((cc.total&&gross)?gross*(cc.active/cc.total):0),cancelVgv=(cc.total&&gross)?gross*(cc.cancel/cc.total):0,age1=validAge(get(row,'Idade 1','Idade')),age2=validAge(get(row,'Idade 2')),ages=[age1,age2].filter(Boolean);return{date,income:n(get(row,'Renda','Renda Bruta','Renda familiar')),car:String(get(row,'Carro 1','Carro','Veículo','Veiculo')||'').trim().toUpperCase(),carYear:Math.round(n(get(row,'Ano carro 1','Ano carro','Ano do carro')))||0,home:profileHome(get(row,'Residência própria','Residencia propria','Casa própria','Casa propria')),rel:profileRel(get(row,'Tipo de relacionamento','Relacionamento','Estado civil')),p1:String(get(row,'Profissão 1','Profissao 1','Profissão','Profissao')||'').trim(),p2:String(get(row,'Profissão 2','Profissao 2')||'').trim(),city:String(get(row,'Cidade')||'').trim(),uf:String(get(row,'UF','Estado')||'').trim().toUpperCase(),age1,age2,ageAvg:ages.length?ages.reduce((s,v)=>s+v,0)/ages.length:0,qual:profileQual(get(row,'Qualificação','Qualificacao','Motivo de qualificação','Motivo de qualificacao')),buyer:cc.active>0,cancelled:cc.cancel>0,activeCount:cc.active,cancelCount:cc.cancel,contractCount:cc.total,value:gross,activeVgv,cancelVgv}}
  function parseRow(row){const date=ymd(get(row,'Data','Data de atendimento')),person=resolvePerson(get(row,'Promotor','Promotor de marketing','Profissional','Captador'));if(!date||!person)return null;const couples=Math.max(1,Math.round(n(get(row,'Casais','Atendimentos')))||1),status=get(row,'Status do contrato','Status contrato'),explicitSales=n(get(row,'Vendas ativas','Vendas Ativas','Vendas')),explicitCancel=n(get(row,'Canceladas','Cancelamentos')),sales=explicitSales||countStatus(status,/^ATIVO\b/),cancelled=explicitCancel||countStatus(status,/^CANCEL/);const qCol=n(get(row,'Q')),nqCol=n(get(row,'NQ')),qual=norm(get(row,'Qualificação','Qualificado','Motivo de qualificação'));let q=qCol,nq=nqCol;if(!q&&!nq&&couples===1){q=qual==='Q'||qual.includes('PERFIL QUALIFICADO')?1:0;nq=qual.startsWith('NQ')?1:0}const general=n(get(row,'VGV bruto','VGV Geral','Valor vendido','VGV')),active=n(get(row,'VGV ativo','VGV Ativo'))||(sales>0?general:0),gift=n(get(row,'Brindes','Valor brindes','Valor em brindes','Valor Brinde')),nt=get(row,'NoTour','No Tour','Descrição de motivo No Tour','Motivo NoTour'),notour=n(nt)||((String(nt).trim()&&couples===1)?1:0);return{date,person,couples,q,nq,sales,cancelled,vgv:active,vgv_general:general,gift,notour,attendances:couples,source:'official-sheet'}}
  function sheetObjects(sheet){const m=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true});if(!m.length)return[];let hi=m.findIndex(r=>r.some(c=>/DATA/.test(norm(c)))&&r.some(c=>/PROMOTOR|PROFISSIONAL|CAPTADOR/.test(norm(c))));if(hi<0)hi=0;const h=m[hi].map((x,i)=>String(x||`campo_${i}`).trim()||`campo_${i}`);return m.slice(hi+1).filter(r=>r.some(v=>String(v).trim())).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
  function aggregate(rows){const map={};rows.forEach(r=>{const k=r.date+'|'+r.person;if(!map[k])map[k]={...r,id:'sheet-'+k};else Object.keys(blank()).forEach(f=>map[k][f]=(Number(map[k][f])||0)+(Number(r[f])||0))});return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date)||a.person.localeCompare(b.person))}
  function blank(){return{couples:0,q:0,nq:0,sales:0,cancelled:0,vgv:0,vgv_general:0,gift:0,notour:0,attendances:0}}
  function sum(rows){return rows.reduce((a,r)=>{Object.keys(blank()).forEach(k=>a[k]+=Number(r[k])||0);return a},blank())}
  async function ensureXlsx(){if(window.XLSX)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=ok;s.onerror=()=>no(new Error('Não consegui carregar o leitor da planilha.'));document.head.appendChild(s)})}
  function showPreview(){const p=$('txImportPreview');if(!candidate||!p)return;const t=candidate.total,m=candidate.meta,coverage=t.couples?candidate.profiles.length/t.couples*100:0;p.style.display='block';p.innerHTML=`<div class="label">CONFERÊNCIA ANTES DE APLICAR</div><div class="txPreviewGrid" style="margin-top:8px"><div class="txPV"><span>Registros válidos</span><b>${num(t.couples)}</b></div><div class="txPV"><span>Perfis detalhados</span><b>${num(candidate.profiles.length)}</b></div><div class="txPV"><span>Q / NQ</span><b>${num(t.q)} / ${num(t.nq)}</b></div><div class="txPV"><span>Vendas</span><b>${num(t.sales)}</b></div><div class="txPV"><span>Cancelamentos</span><b>${num(t.cancelled)}</b></div><div class="txPV"><span>VGV ativo</span><b>${money(t.vgv)}</b></div><div class="txPV"><span>VGV geral</span><b>${money(t.vgv_general)}</b></div></div><div class="tiny" style="margin-top:8px">Período: ${m.from.split('-').reverse().join('/')} → ${m.latest.split('-').reverse().join('/')} • ${num(candidate.groups.length)} grupos Data + Profissional • cobertura de perfil ${coverage.toFixed(1)}% • ${num(candidate.ignored)} linhas ignoradas por falta de Data/Profissional.</div>`}
  async function prepare(file){candidate=null;$('txConfirmSheet').disabled=true;$('txUploadStatus').textContent='Lendo e conferindo a planilha...';try{await ensureXlsx();const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});let source=[],seen=0;wb.SheetNames.forEach(sn=>{const o=sheetObjects(wb.Sheets[sn]);seen+=o.length;source.push(...o)});const parsed=source.map(parseRow).filter(Boolean);if(!parsed.length)throw new Error('Não encontrei registros válidos com Data e Profissional/Promotor.');const profiles=source.map(parseProfileRow).filter(Boolean),groups=aggregate(parsed),total=sum(parsed),dates=parsed.map(r=>r.date).sort(),meta={file:file.name,rows:total.couples,profiles:profiles.length,groups:groups.length,from:dates[0],latest:dates.at(-1),when:new Date().toISOString()};candidate={groups,total,meta,profiles,ignored:Math.max(0,seen-parsed.length)};showPreview();const complete=profiles.length===total.couples;$('txUploadStatus').innerHTML=complete?`<span class="green">✓ Planilha conferida.</span> ${num(profiles.length)} de ${num(total.couples)} casais prontos também para o Perfil Casais.`:`<span class="amber">⚠ Planilha conferida.</span> ${num(profiles.length)} perfis para ${num(total.couples)} casais; o TARGET X não vai inventar campos ausentes.`;$('txConfirmSheet').disabled=false;$('txConfirmSheet').textContent='Confirmar atualização'}catch(e){$('txUploadStatus').innerHTML=`<span class="red">Erro:</span> ${esc(e.message||e)}`;$('txImportPreview').style.display='none'}}
  function confirm(){if(!candidate)return;const oldRows=localStorage.getItem(ROWS),oldMeta=localStorage.getItem(META),oldProfileRows=localStorage.getItem(PSTORE),oldProfileMeta=localStorage.getItem(PMETA);localStorage.setItem(BACKUP,JSON.stringify({rows:oldRows,meta:oldMeta,profileRows:oldProfileRows,profileMeta:oldProfileMeta,when:new Date().toISOString()}));localStorage.setItem(ROWS,JSON.stringify(candidate.groups));localStorage.setItem(META,JSON.stringify(candidate.meta));if(candidate.profiles?.length){localStorage.setItem(PSTORE,JSON.stringify(candidate.profiles));localStorage.setItem(PMETA,JSON.stringify({source:`Planilha oficial: ${candidate.meta.file}`,rows:candidate.profiles.length,through:candidate.meta.latest,from:candidate.meta.from,when:new Date().toISOString(),officialRows:candidate.meta.rows}))}$('txUploadStatus').innerHTML=`<span class="green">✓ Base oficial e Perfil Casais atualizados.</span> ${num(candidate.meta.rows)} registros • ${num(candidate.profiles.length)} perfis • até ${candidate.meta.latest.split('-').reverse().join('/')}.`;$('txConfirmSheet').textContent='Atualizado ✓';$('txUndoSheet').style.display='inline-block';window.TX?.reloadOfficial?.();window.dispatchEvent(new CustomEvent('targetx:profile-updated',{detail:{rows:candidate.profiles.length,official:candidate.meta.rows}}));const activeProfile=document.querySelector('.tab[data-page="clientprofile"].active');if(activeProfile)setTimeout(()=>activeProfile.click(),60);setTimeout(()=>{$('txConfirmSheet').textContent='Confirmar atualização';$('txConfirmSheet').disabled=false},1600)}
  function undo(){const b=JSON.parse(localStorage.getItem(BACKUP)||'null');if(!b)return;if(b.rows===null)localStorage.removeItem(ROWS);else localStorage.setItem(ROWS,b.rows);if(b.meta===null)localStorage.removeItem(META);else localStorage.setItem(META,b.meta);if(b.profileRows===null||b.profileRows===undefined)localStorage.removeItem(PSTORE);else localStorage.setItem(PSTORE,b.profileRows);if(b.profileMeta===null||b.profileMeta===undefined)localStorage.removeItem(PMETA);else localStorage.setItem(PMETA,b.profileMeta);localStorage.removeItem(BACKUP);$('txUndoSheet').style.display='none';$('txUploadStatus').textContent='Última atualização desfeita, inclusive a base do Perfil Casais.';window.TX?.reloadOfficial?.();window.dispatchEvent(new Event('targetx:profile-updated'))}
  function mount(){if($('txUploadBar'))return;const nav=document.querySelector('.tabs');if(!nav)return;const box=document.createElement('div');box.id='txUploadBar';box.className='card';box.innerHTML=`<div><div class="txUpTitle">📊 Base oficial do TARGET X</div><div class="txUpStatus" id="txUploadStatus">Escolha a planilha. A mesma base passa a alimentar também o Perfil Casais.</div></div><div id="txUploadActions"><input id="txSheetFile" type="file" accept=".xlsx,.xls,.csv"><button id="txChooseSheet">Escolher planilha</button><span class="txFileName" id="txFileName">Nenhum arquivo</span><button id="txConfirmSheet" class="primary" disabled>Confirmar atualização</button><button id="txUndoSheet" style="display:${localStorage.getItem(BACKUP)?'inline-block':'none'}">Desfazer última</button></div>`;nav.parentNode.insertBefore(box,nav);const prev=document.createElement('div');prev.id='txImportPreview';box.insertAdjacentElement('afterend',prev);$('txChooseSheet').onclick=()=>$('txSheetFile').click();$('txSheetFile').onchange=()=>{const f=$('txSheetFile').files?.[0];$('txFileName').textContent=f?.name||'Nenhum arquivo';if(f)prepare(f)};$('txConfirmSheet').onclick=confirm;$('txUndoSheet').onclick=undo}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();